---
title: "Teaching"
---

I am mainly teaching at the **European University Flensburg (EUF)**. 
Most of [my courses](https://www.uni-flensburg.de/en/pluralist-economics/teaching/courses-overview) 
have their own separate site — syllabus, assignments, and course-specific materials live there. For the future, I want to keep all generic and general material here, and then link to this hub from my course pages. But you might still find it interesting to browse through the courses. As always, I value any kind of feedback!

## Current courses with open material available

*An overview over my current teaching portfolio can be found [here](https://www.uni-flensburg.de/en/pluralist-economics/teaching/courses-overview).*

For all courses I only link the most recent course site. The respective semester is indicated in brackets after the course name.

- **Theoretical and Empirical Research Methodology - Implementation Lab** (Fall 2025, EUF) — [most recent course site](https://researchmethodology-fall25.netlify.app/).

- **Development Economics** (Fall 2025, EUF) — [most recent course site](https://developmenteconomics-fall25.netlify.app/).

- **Data Science and Econometrics for International Business** (Spring 2026, EUF) — [most recent course site](https://quantitative-data-analysis-spring26.netlify.app/).

---

I am currently working on making all my teaching ressources openly available. 
Feedback of any kind is warmly appreciated.
