{
  "hash": "eae4c01e79594b32379099b56849dede",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logistic Regression for Binary Outcomes in R\"\ndescription: \"Understand why OLS fails for binary outcomes, fit logistic regression with glm(), and translate log-odds into predicted probabilities and average marginal effects.\"\nauthor: \"Claudius Gräbner-Radkowitsch\"\ndate: 2026-06-16\ndate-modified: 2026-06-16\nimage: ../../assets/images/r-programming.png\n\nlearning-objectives:\n  - \"Explain why OLS produces invalid predictions and unreliable standard errors when the outcome is binary\"\n  - \"Fit a logistic regression model in R using `glm(..., family = binomial)`\"\n  - \"Interpret logistic regression output at three levels: log-odds, odds ratios, and predicted probabilities\"\n  - \"Compute average marginal effects with `marginaleffects::avg_slopes()` and explain when they are more useful than odds ratios\"\n\ncategories:\n  - R\n  - regression\n  - statistics\n  - MA\n  - tutorial\n\nlevel:\n  - MA\n\ncontent-type: tutorial\n\ncitation:\n  type: entry\n  container-title: \"Methods Hub\"\n  title: \"Logistic Regression for Binary Outcomes in R\"\n  editor:\n    - name: \"Claudius Gräbner-Radkowitsch\"\n  url: https://euf-methodology-hub.netlify.app/resources/r-programming/logistic-regression-in-r\n---\n\n# Introduction\n\nMany outcomes of interest in economics, political science, and business are **binary** — a firm either exits the market or it does not; a loan is either repaid or it defaults; a voter either turns out or abstains. The familiar linear regression model runs into fundamental problems with such outcomes: it produces predicted probabilities outside [0, 1] and generates invalid standard errors.\n\n**Logistic regression** solves both problems by modelling the probability of the outcome through a transformation that keeps predictions bounded between 0 and 1. The tradeoff is a more complex interpretation: instead of reading off the effect of X on Y directly, we work with log-odds, odds ratios, and — most practically — predicted probabilities.\n\n## Research question\n\n> *Can we predict which firms are likely to exit the market in the next year?*\n\n## Data and packages\n\nWe use the `bisnode-firms` dataset from Békés & Kézdi (2021). It contains roughly 17,500 Hungarian manufacturing and services firms. The outcome variable `exit` is a binary indicator equal to 1 if the firm closed in the following year.\n\n::: {.callout-note}\n## Getting the data\nDownload `bisnode-firms.csv` from [gabors-data-analysis.com](https://gabors-data-analysis.com/datasets/#bisnode-firms) and place it in a `data/` subfolder next to this file. The dataset is distributed with the Békés & Kézdi textbook under an open data licence.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(modelsummary)\nlibrary(marginaleffects)\nlibrary(broom)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirms <- read_csv(\"data/bisnode-firms.csv\")\nglimpse(firms)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 17,506\nColumns: 11\n$ comp_id       <dbl> 1002029, 1011889, 1014183, 1018301, 1022796, 1035705, 10…\n$ exit          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,…\n$ sales_log     <dbl> 13.943477, 12.980031, 11.773208, 8.813174, 10.169549, 10…\n$ employees_log <dbl> -0.78015860, 0.48317409, -0.33508429, -1.87877086, -2.48…\n$ profit_margin <dbl> 0.008554417, 0.223101892, -0.018128871, -0.164738285, -0…\n$ age           <dbl> 6, 20, 11, 8, 11, 1, 14, 5, 2, 4, 2, 1, 2, 4, 16, 1, 23,…\n$ liquidity     <dbl> 1.69277357, 8.46944789, 24.16025018, 3.05624997, 0.90785…\n$ foreign       <dbl> 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,…\n$ female_ceo    <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,…\n$ industry      <dbl> 27, 55, 55, 56, 56, 56, 29, 56, 56, 27, 41, 55, 56, 28, …\n$ urban         <dbl> 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,…\n```\n\n\n:::\n:::\n\n\nHow common is firm exit in this sample?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirms |>\n  count(exit) |>\n  mutate(share = n / sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n   exit     n  share\n  <dbl> <int>  <dbl>\n1     0 16294 0.931 \n2     1  1212 0.0692\n```\n\n\n:::\n:::\n\n\nExit events are relatively rare — this is typical of survival data.\n\n# Why OLS Fails for Binary Outcomes\n\n## The Linear Probability Model\n\nThe simplest approach is to regress the binary outcome on predictors with OLS. This is called the **Linear Probability Model (LPM)**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlpm <- lm(exit ~ sales_log + profit_margin + employees_log, data = firms)\nsummary(lpm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = exit ~ sales_log + profit_margin + employees_log, \n    data = firms)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.27563 -0.07935 -0.05414 -0.03527  1.04989 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    0.216657   0.022001   9.848  < 2e-16 ***\nsales_log     -0.013902   0.001729  -8.041 9.45e-16 ***\nprofit_margin -0.087885   0.005908 -14.875  < 2e-16 ***\nemployees_log  0.005976   0.002556   2.338   0.0194 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2498 on 17502 degrees of freedom\nMultiple R-squared:  0.03178,\tAdjusted R-squared:  0.03162 \nF-statistic: 191.5 on 3 and 17502 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe LPM coefficient on `profit_margin` is -0.088: a one-unit increase in profit margin is associated with a -0.088 change in the **probability** of exit. Interpretation is direct — but does it work?\n\n## Problem 1: out-of-bounds predictions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlpm_fitted <- augment(lpm, data = firms)\n\nlpm_fitted |>\n  summarise(\n    min_pred     = min(.fitted),\n    max_pred     = max(.fitted),\n    n_below_zero = sum(.fitted < 0),\n    n_above_one  = sum(.fitted > 1)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  min_pred max_pred n_below_zero n_above_one\n     <dbl>    <dbl>        <int>       <int>\n1  -0.0651    0.277          338           0\n```\n\n\n:::\n:::\n\n\nSome predicted \"probabilities\" are below 0 or above 1 — mathematically impossible.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(lpm_fitted, aes(x = sales_log, y = .fitted)) +\n  geom_point(alpha = 0.2, size = 0.8, color = \"#2c7bb6\") +\n  geom_hline(yintercept = c(0, 1), linetype = \"dashed\", color = \"firebrick\") +\n  annotate(\"label\", x = max(firms$sales_log, na.rm = TRUE) - 1,\n           y = -0.05, label = \"Impossible: P < 0\",\n           color = \"firebrick\", size = 3) +\n  labs(\n    title = \"LPM: fitted probabilities of firm exit\",\n    x = \"Log sales\", y = \"Predicted P(exit = 1)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![LPM predicted probabilities of firm exit. Values outside [0, 1] are impossible.](logistic-regression-in-r_files/figure-html/fig-lpm-bounds-1.png){#fig-lpm-bounds width=672}\n:::\n:::\n\n\n## Problem 2: heteroskedastic errors\n\nWhen Y is binary, the variance of the error term depends on X by construction:\n\n$$\\text{Var}(\\varepsilon_i \\mid x_i) = \\hat{P}_i(1 - \\hat{P}_i)$$\n\nThis violates the homoskedasticity assumption, making OLS standard errors invalid.\n\n::: {.callout-note}\nDespite these problems, the LPM is widely used in economics, especially with panel data, because it is easy to estimate and interpret. It can serve as a useful benchmark. Always be aware of its limitations when predicted values approach 0 or 1.\n:::\n\n# Logistic Regression: Intuition\n\n## The logistic function\n\nWe need a function that maps any real number to a probability in [0, 1]. The **logistic (sigmoid) function** does exactly this:\n\n$$\\sigma(z) = \\frac{e^z}{1 + e^z}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsigma <- function(z) exp(z) / (1 + exp(z))\n\ntibble(z = seq(-6, 6, by = 0.05)) |>\n  mutate(prob = sigma(z)) |>\n  ggplot(aes(z, prob)) +\n  geom_line(color = \"#1a9641\", linewidth = 1.3) +\n  geom_hline(yintercept = c(0, 0.5, 1), linetype = \"dashed\", color = \"grey60\") +\n  labs(\n    title = \"The logistic function\",\n    x = \"z (linear combination of predictors)\",\n    y = \"Predicted probability\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![The logistic function maps any real number to a value in (0, 1).](logistic-regression-in-r_files/figure-html/fig-logistic-1.png){#fig-logistic width=672}\n:::\n:::\n\n\nThe model sets $z = \\beta_0 + \\beta_1 x_1 + \\ldots$, so:\n\n$$\\hat{P}(\\text{exit} = 1 \\mid \\mathbf{x}) = \\frac{e^{\\mathbf{X}\\boldsymbol{\\beta}}}{1 + e^{\\mathbf{X}\\boldsymbol{\\beta}}}$$\n\n## The logit link\n\nRearranging gives the **logit link** — the log-odds:\n\n$$\\ln\\left(\\frac{P}{1-P}\\right) = \\beta_0 + \\beta_1 x_1 + \\beta_2 x_2 + \\ldots$$\n\n| P(exit) | Odds | Log-odds |\n|:---:|:---:|:---:|\n| 0.10 | 0.11 | −2.20 |\n| 0.25 | 0.33 | −1.10 |\n| 0.50 | 1.00 | 0.00 |\n| 0.75 | 3.00 | 1.10 |\n| 0.90 | 9.00 | 2.20 |\n\nLogistic regression is estimated by **maximum likelihood** — not OLS. R's `glm()` handles the estimation automatically.\n\n# Logistic Regression in R\n\n## Fitting the model\n\nThe syntax mirrors `lm()`. The critical addition is `family = binomial`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit_model <- glm(exit ~ sales_log + profit_margin + employees_log,\n                   family = binomial,\n                   data = firms)\n\nsummary(logit_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = exit ~ sales_log + profit_margin + employees_log, \n    family = binomial, data = firms)\n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   -1.048479   0.331230  -3.165  0.00155 ** \nsales_log     -0.168696   0.026067  -6.472  9.7e-11 ***\nprofit_margin -1.047630   0.085995 -12.183  < 2e-16 ***\nemployees_log  0.006127   0.043090   0.142  0.88694    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 8810.8  on 17505  degrees of freedom\nResidual deviance: 8333.5  on 17502  degrees of freedom\nAIC: 8341.5\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n::: {.callout-important}\nIf you forget `family = binomial`, R silently fits a Gaussian (OLS) model on your binary outcome. Always verify your model specification.\n:::\n\n## LPM vs. logit side by side\n\n\n::: {#tbl-lpm-logit .cell tbl-cap='Firm exit: LPM vs. logistic regression'}\n\n```{.r .cell-code}\nmodelsummary(\n  list(\"LPM\" = lpm, \"Logit\" = logit_model),\n  stars = TRUE,\n  gof_map = c(\"nobs\", \"r.squared\", \"logLik\", \"AIC\"),\n  title = \"Firm exit: LPM vs. logistic regression\"\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_z7kl34dv8np5eem4c1zv = TinyTable.createTableFunctions(\"tinytable_z7kl34dv8np5eem4c1zv\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '11', j: 2 }, { i: '11', j: 3 } ], css_id: 'tinytable_css_otd0upj9mzczpipxxb86',}, \n          { positions: [ { i: '8', j: 2 }, { i: '8', j: 3 } ], css_id: 'tinytable_css_5lfrvfucjpgj6gr5cc2j',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 } ], css_id: 'tinytable_css_i05p030eql6tjrpdhm7b',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_7fhr14rvnhhkhxbykfsi',}, \n          { positions: [ { i: '11', j: 1 } ], css_id: 'tinytable_css_a8e2ye4lq79l8xtzj9j7',}, \n          { positions: [ { i: '8', j: 1 } ], css_id: 'tinytable_css_upn1x4yfjk6tcokzjdui',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 } ], css_id: 'tinytable_css_7ncey9o6ug53951xhv01',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_qn9c7a8oskd5cl8aua1d',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_z7kl34dv8np5eem4c1zv.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_z7kl34dv8np5eem4c1zv td.tinytable_css_otd0upj9mzczpipxxb86, #tinytable_z7kl34dv8np5eem4c1zv th.tinytable_css_otd0upj9mzczpipxxb86 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_z7kl34dv8np5eem4c1zv td.tinytable_css_5lfrvfucjpgj6gr5cc2j, #tinytable_z7kl34dv8np5eem4c1zv th.tinytable_css_5lfrvfucjpgj6gr5cc2j {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_z7kl34dv8np5eem4c1zv td.tinytable_css_i05p030eql6tjrpdhm7b, #tinytable_z7kl34dv8np5eem4c1zv th.tinytable_css_i05p030eql6tjrpdhm7b { text-align: center }\n    #tinytable_z7kl34dv8np5eem4c1zv td.tinytable_css_7fhr14rvnhhkhxbykfsi, #tinytable_z7kl34dv8np5eem4c1zv th.tinytable_css_7fhr14rvnhhkhxbykfsi {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_z7kl34dv8np5eem4c1zv td.tinytable_css_a8e2ye4lq79l8xtzj9j7, #tinytable_z7kl34dv8np5eem4c1zv th.tinytable_css_a8e2ye4lq79l8xtzj9j7 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_z7kl34dv8np5eem4c1zv td.tinytable_css_upn1x4yfjk6tcokzjdui, #tinytable_z7kl34dv8np5eem4c1zv th.tinytable_css_upn1x4yfjk6tcokzjdui {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_z7kl34dv8np5eem4c1zv td.tinytable_css_7ncey9o6ug53951xhv01, #tinytable_z7kl34dv8np5eem4c1zv th.tinytable_css_7ncey9o6ug53951xhv01 { text-align: left }\n    #tinytable_z7kl34dv8np5eem4c1zv td.tinytable_css_qn9c7a8oskd5cl8aua1d, #tinytable_z7kl34dv8np5eem4c1zv th.tinytable_css_qn9c7a8oskd5cl8aua1d {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_z7kl34dv8np5eem4c1zv\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Firm exit: LPM vs. logistic regression</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">LPM</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Logit</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='3'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">0.217***</td>\n                  <td data-row=\"1\" data-col=\"3\">-1.048**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.022)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.331)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">sales_log</td>\n                  <td data-row=\"3\" data-col=\"2\">-0.014***</td>\n                  <td data-row=\"3\" data-col=\"3\">-0.169***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.002)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.026)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">profit_margin</td>\n                  <td data-row=\"5\" data-col=\"2\">-0.088***</td>\n                  <td data-row=\"5\" data-col=\"3\">-1.048***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.006)</td>\n                  <td data-row=\"6\" data-col=\"3\">(0.086)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">employees_log</td>\n                  <td data-row=\"7\" data-col=\"2\">0.006*</td>\n                  <td data-row=\"7\" data-col=\"3\">0.006</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.003)</td>\n                  <td data-row=\"8\" data-col=\"3\">(0.043)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"9\" data-col=\"2\">17506</td>\n                  <td data-row=\"9\" data-col=\"3\">17506</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">R2</td>\n                  <td data-row=\"10\" data-col=\"2\">0.032</td>\n                  <td data-row=\"10\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Log.Lik.</td>\n                  <td data-row=\"11\" data-col=\"2\">-556.349</td>\n                  <td data-row=\"11\" data-col=\"3\">-4166.748</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nNote: logit reports log-likelihood and AIC rather than R². These are the relevant fit statistics for maximum likelihood models.\n\n# Interpretation\n\n## Level 1: log-odds (raw coefficients)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(logit_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)     sales_log profit_margin employees_log \n -1.048478951  -0.168695919  -1.047629865   0.006126538 \n```\n\n\n:::\n:::\n\n\nThe coefficient on `profit_margin` is -1.048: a one-unit increase in `profit_margin` changes the **log-odds** of exit by that amount. The direction is clear, but the magnitude is hard to interpret intuitively.\n\n## Level 2: odds ratios\n\nExponentiate the coefficients:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(coef(logit_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)     sales_log profit_margin employees_log \n    0.3504704     0.8447657     0.3507681     1.0061453 \n```\n\n\n:::\n:::\n\n\nThe odds ratio for `profit_margin` is 0.351: a one-unit increase in profit margin multiplies the odds of exit by 0.351, reducing them by 64.9%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(confint(logit_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  2.5 %    97.5 %\n(Intercept)   0.1821600 0.6674216\nsales_log     0.8029502 0.8893463\nprofit_margin 0.2961005 0.4147961\nemployees_log 0.9243338 1.0944416\n```\n\n\n:::\n:::\n\n\n## Level 3: predicted probabilities\n\nPredicted probabilities are usually the most useful form for communicating results.\n\n**For the observed data:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirms <- firms |>\n  mutate(pred_prob = predict(logit_model, type = \"response\"))\n\nfirms |>\n  group_by(exit) |>\n  summarise(mean_pred_prob = mean(pred_prob) |> round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n   exit mean_pred_prob\n  <dbl>          <dbl>\n1     0          0.067\n2     1          0.099\n```\n\n\n:::\n:::\n\n\nFirms that actually exited had, on average, a higher predicted exit probability than survivors — the model is doing something sensible.\n\n**For specific scenarios:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscenarios <- tibble(\n  label         = c(\"Profitable, large\", \"Loss-making, small\"),\n  sales_log     = c(11, 9),\n  employees_log = c(4, 2),\n  profit_margin = c(0.10, -0.15)\n)\n\nscenarios |>\n  mutate(\n    pred_prob = predict(logit_model, newdata = scenarios, type = \"response\") |> round(3)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  label              sales_log employees_log profit_margin pred_prob\n  <chr>                  <dbl>         <dbl>         <dbl>     <dbl>\n1 Profitable, large         11             4          0.1      0.048\n2 Loss-making, small         9             2         -0.15     0.083\n```\n\n\n:::\n:::\n\n\n**Visualising the probability curve:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- tibble(\n  profit_margin = seq(-0.5, 0.5, by = 0.01),\n  sales_log     = mean(firms$sales_log, na.rm = TRUE),\n  employees_log = mean(firms$employees_log, na.rm = TRUE)\n) |>\n  mutate(pred_prob = predict(logit_model, newdata = pick(everything()), type = \"response\"))\n\nggplot(grid, aes(x = profit_margin, y = pred_prob)) +\n  geom_line(color = \"#1a9641\", linewidth = 1.2) +\n  geom_hline(yintercept = c(0, 1), linetype = \"dashed\", color = \"grey60\") +\n  labs(\n    title = \"Predicted probability of exit vs. profit margin\",\n    subtitle = \"Other variables held at their mean\",\n    x = \"Profit margin\", y = \"P(exit = 1)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Predicted probability of firm exit across values of profit margin, other variables held at their mean.](logistic-regression-in-r_files/figure-html/fig-prob-curve-1.png){#fig-prob-curve width=672}\n:::\n:::\n\n\n## Average Marginal Effects\n\nBecause logit is non-linear, the marginal effect of a predictor varies across observations. The **Average Marginal Effect (AME)** averages these individual marginal effects across the sample:\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_slopes(logit_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n          Term  Estimate Std. Error       z Pr(>|z|)     S    2.5 %   97.5 %\n employees_log  0.000381    0.00268   0.142    0.887   0.2 -0.00487  0.00563\n profit_margin -0.065177    0.00546 -11.927   <0.001 106.5 -0.07589 -0.05447\n sales_log     -0.010495    0.00163  -6.445   <0.001  33.0 -0.01369 -0.00730\n\nType: response\nComparison: dY/dX\n```\n\n\n:::\n:::\n\n\nThe AME for `profit_margin` directly answers: *\"On average across all firms, a one-unit increase in profit margin is associated with a [AME] change in the probability of exit.\"* This is directly comparable to the LPM coefficient.\n\n# Summary\n\n| Approach | Estimate | Interpretation |\n|---|---|---|\n| LPM | OLS coefficient | Change in P(Y=1) — direct but can be out of bounds |\n| Logit — log-odds | glm coefficient | Direction clear; magnitude not intuitive |\n| Logit — odds ratio | exp(coefficient) | Proportional change in odds |\n| Logit — predicted prob | `predict(type=\"response\")` | Most useful for scenarios and communication |\n| Logit — AME | `avg_slopes()` | Average probability change; comparable to LPM |\n\n# Practice\n\nApply these skills in the [exercise on predicting firm exit](exercise-logistic-regression-firm-exit.qmd).\n\n# Further Reading\n\n- Békés, G. & Kézdi, G. (2021). *Data Analysis for Business, Economics, and Policy*. Ch. 11. [gabors-data-analysis.com](https://gabors-data-analysis.com)\n- James, G., Witten, D., Hastie, T., & Tibshirani, R. (2021). *An Introduction to Statistical Learning*. Ch. 4. [statlearning.com](https://www.statlearning.com)\n",
    "supporting": [
      "logistic-regression-in-r_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}