{
  "hash": "20b1fd291e58d12ac03b684e8d814f16",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Linear Regression in R\"\ndescription: \"Practical implementation of simple and multiple linear regression in R: fitting models with lm(), interpreting coefficients, computing R², understanding omitted variable bias, applying log and quadratic transformations, and reading diagnostic plots.\"\nauthor: \"Claudius Gräbner-Radkowitsch\"\ndate: 2026-06-16\ndate-modified: 2026-06-16\nimage: ../../assets/images/placeholder.png\n\nlearning-objectives:\n  - \"Fit simple and multiple linear regression models using `lm()` and interpret the coefficients\"\n  - \"Calculate and interpret R² manually and with R's built-in functions\"\n  - \"Explain omitted variable bias and demonstrate it with an example\"\n  - \"Apply log and quadratic transformations to linearize non-linear relationships\"\n\ncategories:\n  - R\n  - regression\n  - statistics\n  - BA\n  - tutorial\n\nlevel:\n  - BA\n\ncontent-type: tutorial\n\ncitation:\n  type: entry\n  container-title: \"Methods Hub\"\n  title: \"Linear Regression in R\"\n  editor:\n    - name: \"Claudius Gräbner-Radkowitsch\"\n  url: https://euf-methodology-hub.netlify.app/resources/r-programming/linear-regression-r\n---\n\n# Introduction\n\nIn this tutorial, we will focus on the practical aspects of implementing linear regression models in R.\nThe tutorial extends simple linear regression to multiple regression.\nWe'll also explore how to handle non-linear relationships through data transformation practically and discuss the important concept of omitted variable bias.\n\n## Prerequisites\n\n- Basic understanding of linear regression concepts\n- Familiarity with R and RStudio, as developed in previous tutorials\n- Understanding of basic statistical concepts (mean, variance, correlation)\n\n# Setup and Data\n\n## Loading Required Packages\n\nIn this tutorial we will use the following libraries:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages explicitly\nlibrary(ggplot2)     # For data visualization\nlibrary(dplyr)       # For data manipulation\nlibrary(readr)       # For reading CSV files\nlibrary(moderndive)  # For regression tables\nlibrary(broom)       # For model summaries\nlibrary(here)        # For file paths\nlibrary(kableExtra)  # For nice HTML tables, optional for you\n```\n:::\n\n\n## Loading the Datasets\n\nFor this tutorial, we'll work with the following business data sets that demonstrate different aspects of regression analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the three datasets\nmarketing_data <- read_csv(\"data/marketing_roi.csv\")\npricing_data <- read_csv(\"data/pricing_strategy.csv\")\nhr_data <- read_csv(\"data/hr_salaries.csv\")\nfirm_growth_data <- read_csv(\"data/firm_growth.csv\")\nmarketing_efficiency_data <- read_csv(\"data/marketing_efficiency.csv\")\n```\n:::\n\n\n# Simple Linear Regression\n\nLet's start with the fundamentals of simple linear regression using the marketing dataset.\nIt is always a good idea to first inspect the data set you are using:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(marketing_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 36\nColumns: 3\n$ ad_spend        <dbl> 10751.550, 20766.103, 13179.538, 22660.348, 23809.346,…\n$ website_traffic <dbl> 11003.952, 16667.299, 9407.983, 18692.329, 17995.468, …\n$ sales_revenue   <dbl> 46252.00, 82831.26, 44909.07, 83920.10, 84140.37, 3299…\n```\n\n\n:::\n:::\n\n\n\n### Basic Implementation\n\nTo fit a linear regression model we use the function `lm()` (which stands for \"linear model\").\nHere we conduct a regression with sales revenue as the dependent, and ad spending as the independent variable:\n\n$$SALES = \\beta_0 + \\beta_1 EXP_{Ads} + \\epsilon $$\n\nTo this end we specify the LHS and RHS of the regression equation, separated by a `~`, through the argument `formula`.\nThe variable names must be the same as in the data set we use, and which we specify through the argument `data`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simple regression: Sales Revenue ~ Ad Spend\nmodel_simple <- lm(formula = sales_revenue ~ ad_spend, data = marketing_data)\nmodel_simple\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sales_revenue ~ ad_spend, data = marketing_data)\n\nCoefficients:\n(Intercept)     ad_spend  \n  14969.808        2.945  \n```\n\n\n:::\n:::\n\n\nYou can get additional information by using the function `summary()` on the\nresulting object, or the function `get_regression_table` from the package `moderndive`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Display results using moderndive for clean output\nget_regression_table(model_simple) %>%\n  kable(caption = \"Simple Linear Regression: Sales Revenue ~ Ad Spend\") %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\", \"condensed\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Simple Linear Regression: Sales Revenue ~ Ad Spend</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std_error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p_value </th>\n   <th style=\"text-align:right;\"> lower_ci </th>\n   <th style=\"text-align:right;\"> upper_ci </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> intercept </td>\n   <td style=\"text-align:right;\"> 14969.808 </td>\n   <td style=\"text-align:right;\"> 2351.591 </td>\n   <td style=\"text-align:right;\"> 6.366 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 10190.801 </td>\n   <td style=\"text-align:right;\"> 19748.815 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ad_spend </td>\n   <td style=\"text-align:right;\"> 2.945 </td>\n   <td style=\"text-align:right;\"> 0.133 </td>\n   <td style=\"text-align:right;\"> 22.139 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 2.674 </td>\n   <td style=\"text-align:right;\"> 3.215 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n### Interpreting the basic regression model\n\nWe estimated two main parameters of interest, the intercept $\\beta_0$ and the slope $\\beta_1$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract key values for interpretation\nintercept <- round(coef(model_simple)[1], 0)\nslope <- round(coef(model_simple)[2], 3)\n```\n:::\n\n\nIn our fitted model we have:\n\n- $\\hat{\\beta_0}=$ 1.497\\times 10^{4}\n- $\\hat{\\beta_1}=$ 2.945\n\nThe means that:\n\n- **Base Revenue**: Even without advertising, we can expect a baseline revenue of 14,970 EUR (although intercepts must be interpreted with great care)\n- **Return on Investment**: Every EUR spent on advertising is associated with on average approximately 2.94 EUR in additional sales revenue\n\n### Visualizing the Regression\n\nOne of the most useful features of `ggplot2` is the `geom_smooth()` function, which can automatically fit and display regression lines:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create scatter plot with regression line\nggplot(marketing_data, aes(x = ad_spend, y = sales_revenue)) +\n  geom_point(alpha = 0.7) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"blue\", linewidth = 1) +\n  labs(\n    title = \"Sales Revenue vs Ad Spend\",\n    x = \"Ad Spend (EUR)\",\n    y = \"Sales Revenue (EUR)\",\n    caption = \"Blue line shows linear regression fit\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](linear-regression-r_files/figure-html/simple-viz-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-tip}\n## Understanding geom_smooth()\n\n- `method = \"lm\"` fits a linear model\n- `se = FALSE` removes the confidence interval bands\n- `se = TRUE` (default) shows 95% confidence intervals\n- You can also use `method = \"loess\"` for flexible, non-parametric fits\n:::\n\n# Multiple Linear Regression\n\nReal-world relationships often involve multiple variables. Let's extend our model to include website traffic.\n\n### Adding a Second Predictor\n\nConceptually, we are now estimating the following model:\n\n$$SALES = \\beta_0 + \\beta_1 EXP_{Ads} + \\beta_2 TRAFFIC + \\epsilon $$\n\nTo do this in `R`, we proceed exactly as before and just add the new independent variable to the `formula`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Multiple regression: Sales ~ Ad Spend + Website Traffic\nmodel_multiple <- lm(sales_revenue ~ ad_spend + website_traffic,\n                    data = marketing_data)\n\nget_regression_table(model_multiple) %>%\n  kable(caption = \"Multiple Linear Regression: Sales Revenue ~ Ad Spend + Website Traffic\") %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\", \"condensed\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Multiple Linear Regression: Sales Revenue ~ Ad Spend + Website Traffic</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std_error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p_value </th>\n   <th style=\"text-align:right;\"> lower_ci </th>\n   <th style=\"text-align:right;\"> upper_ci </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> intercept </td>\n   <td style=\"text-align:right;\"> 12965.099 </td>\n   <td style=\"text-align:right;\"> 2398.245 </td>\n   <td style=\"text-align:right;\"> 5.406 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 8085.833 </td>\n   <td style=\"text-align:right;\"> 17844.365 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ad_spend </td>\n   <td style=\"text-align:right;\"> 2.216 </td>\n   <td style=\"text-align:right;\"> 0.349 </td>\n   <td style=\"text-align:right;\"> 6.341 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 1.505 </td>\n   <td style=\"text-align:right;\"> 2.927 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> website_traffic </td>\n   <td style=\"text-align:right;\"> 0.985 </td>\n   <td style=\"text-align:right;\"> 0.440 </td>\n   <td style=\"text-align:right;\"> 2.236 </td>\n   <td style=\"text-align:right;\"> 0.032 </td>\n   <td style=\"text-align:right;\"> 0.089 </td>\n   <td style=\"text-align:right;\"> 1.881 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Interpreting Both Predictors\n\nWe now estimated *three* main parameters of interest, the intercept $\\beta_0$ and two slope parameters $\\beta_1$, and $\\beta_2$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract coefficients for interpretation\nintercept_mult <- round(coef(model_multiple)[1], 0)\nad_coef_mult <- round(coef(model_multiple)[2], 3)\ntraffic_coef <- round(coef(model_multiple)[3], 3)\n```\n:::\n\n\nIn our fitted model we have:\n\n- $\\hat{\\beta_0}=$ 1.2965\\times 10^{4}\n- $\\hat{\\beta_1}=$ 2.216\n- $\\hat{\\beta_2}=$ 0.985\n\nIn the multiple regression framework the interpretation of the coefficients changes slightly, as we now estimate *ceteris paribus* effects, sometimes also called *direct effects*, in contrast to the *total association* that was our focus in the simple regression framework.\n\nMore precisely, the estimates in the multiple regression framework control for changes in the other variables.\nThe means that these are the changes we can expect in the dependent variable, if the independent variable changed by one unit, and all other variables stayed the same.\n\nMore precisely:\n\n- $\\hat{\\beta_1}=$ 2.216 means that for every increase of 1 EUR in ad spending, there is an associated increase of revenue of, on\naverage and ceteris paribus, 2.216 EUR.\n\n- $\\hat{\\beta_2}=$ 0.985 means that every increase of website traffic by 1 person is associated with an increase of revenue of, on\naverage and ceteris paribus, 0.985 EUR.\n\nNote that the *indirect effect* of ad spending is different to the direct effect estimated!\nMore precisely, the direct effect of advertising (2.216 EUR) is smaller than the total effect (2.945 EUR) because some of advertising's impact works through increased website traffic, and the multiple regression framework helps us to identify these different channels.\n\nWe also say that the simple regression model was *confounding* the effects of ad spend and website traffic!\n\n## Omitted Variable Bias\n\nThis brings us to one of the most important concepts in regression analysis:\n*omitted variable bias*.\nIt occurs when both of the following conditions are met:\n\n- There is a variable that correlates with our dependent variable **and**...\n- also correlates with one of our independent variables.\n\n### The Theory\n\nWhen we omit a relevant variable from our regression, the coefficients of included variables become **biased**. The bias depends on:\n\n1. How strongly the omitted variable affects the outcome\n2. How correlated the omitted variable is with included variables\n\n### Example 1: Marketing Data - Coefficient Size Change\n\nIn our previous example, $\\hat{\\beta}_1$ for the simple model was\n2.94\nand for the multiple model it was\n2.22,\nmeaning that we have a total bias of\n0.73.\n\nSince website traffic is positively correlated with ad spend AND positively affects sales, the simple model **overestimates** the effect of ad spend.\n\n### Example 2: When Coefficients Change Sign Completely\n\nSometimes omitted variable bias is so severe that it completely changes the **direction** of the relationship. Let's look at an example using beer consumption data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_data <- DataScienceExercises::beer %>%\n  dplyr::mutate(income = income/1000)\n\nmodel_1 <- lm(\n  formula = consumption ~ income,\n  data=beer_data)\nmodel_2 <- lm(\n  formula = consumption ~ income + price,\n  data=beer_data)\nmodel_3 <- lm(\n  formula = consumption ~ income + price + price_liquor,\n  data=beer_data)\nmodel_4 <- lm(\n  formula = consumption ~ income + price  + price_liquor + price_other,\n  data=beer_data)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary::modelsummary(\n  models = list(\n    \"Simple\"=model_1,\n    \"Model 2\"=model_2,\n    \"Model 3\"=model_3,\n    \"Model 4\"=model_4),\n  gof_map = c(\"nobs\", \"r.squared\"),\n  stars = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_7ldnwwuox7a55v8gvycd = TinyTable.createTableFunctions(\"tinytable_7ldnwwuox7a55v8gvycd\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 2 }, { i: '12', j: 3 }, { i: '12', j: 4 }, { i: '12', j: 5 } ], css_id: 'tinytable_css_d1ah6oyjhitnw10pzrr6',}, \n          { positions: [ { i: '10', j: 2 }, { i: '10', j: 3 }, { i: '10', j: 4 }, { i: '10', j: 5 } ], css_id: 'tinytable_css_ysvqqi3kanc7ktta5thf',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '11', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '11', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 }, { i: '7', j: 4 }, { i: '8', j: 4 }, { i: '9', j: 4 }, { i: '11', j: 4 }, { i: '1', j: 5 }, { i: '2', j: 5 }, { i: '3', j: 5 }, { i: '4', j: 5 }, { i: '5', j: 5 }, { i: '6', j: 5 }, { i: '7', j: 5 }, { i: '8', j: 5 }, { i: '9', j: 5 }, { i: '11', j: 5 } ], css_id: 'tinytable_css_rxdtpgy2mvichhznm5h8',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 } ], css_id: 'tinytable_css_qu3uik1h0oqcs3zvs9w4',}, \n          { positions: [ { i: '12', j: 1 } ], css_id: 'tinytable_css_2h935v7qxsiol9soscru',}, \n          { positions: [ { i: '10', j: 1 } ], css_id: 'tinytable_css_didtde1hxu04rj0u0se8',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 } ], css_id: 'tinytable_css_a3qa4a4bsils29lxs16b',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_eequmsikvaj65r0g3o9f',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_7ldnwwuox7a55v8gvycd.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_7ldnwwuox7a55v8gvycd td.tinytable_css_d1ah6oyjhitnw10pzrr6, #tinytable_7ldnwwuox7a55v8gvycd th.tinytable_css_d1ah6oyjhitnw10pzrr6 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_7ldnwwuox7a55v8gvycd td.tinytable_css_ysvqqi3kanc7ktta5thf, #tinytable_7ldnwwuox7a55v8gvycd th.tinytable_css_ysvqqi3kanc7ktta5thf {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_7ldnwwuox7a55v8gvycd td.tinytable_css_rxdtpgy2mvichhznm5h8, #tinytable_7ldnwwuox7a55v8gvycd th.tinytable_css_rxdtpgy2mvichhznm5h8 { text-align: center }\n    #tinytable_7ldnwwuox7a55v8gvycd td.tinytable_css_qu3uik1h0oqcs3zvs9w4, #tinytable_7ldnwwuox7a55v8gvycd th.tinytable_css_qu3uik1h0oqcs3zvs9w4 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_7ldnwwuox7a55v8gvycd td.tinytable_css_2h935v7qxsiol9soscru, #tinytable_7ldnwwuox7a55v8gvycd th.tinytable_css_2h935v7qxsiol9soscru {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_7ldnwwuox7a55v8gvycd td.tinytable_css_didtde1hxu04rj0u0se8, #tinytable_7ldnwwuox7a55v8gvycd th.tinytable_css_didtde1hxu04rj0u0se8 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_7ldnwwuox7a55v8gvycd td.tinytable_css_a3qa4a4bsils29lxs16b, #tinytable_7ldnwwuox7a55v8gvycd th.tinytable_css_a3qa4a4bsils29lxs16b { text-align: left }\n    #tinytable_7ldnwwuox7a55v8gvycd td.tinytable_css_eequmsikvaj65r0g3o9f, #tinytable_7ldnwwuox7a55v8gvycd th.tinytable_css_eequmsikvaj65r0g3o9f {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_7ldnwwuox7a55v8gvycd\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Simple</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Model 2</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Model 3</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Model 4</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='5'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">96.439***</td>\n                  <td data-row=\"1\" data-col=\"3\">57.160***</td>\n                  <td data-row=\"1\" data-col=\"4\">67.440**</td>\n                  <td data-row=\"1\" data-col=\"5\">82.159***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(7.521)</td>\n                  <td data-row=\"2\" data-col=\"3\">(9.468)</td>\n                  <td data-row=\"2\" data-col=\"4\">(19.995)</td>\n                  <td data-row=\"2\" data-col=\"5\">(17.962)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">income</td>\n                  <td data-row=\"3\" data-col=\"2\">-1.237***</td>\n                  <td data-row=\"3\" data-col=\"3\">2.580**</td>\n                  <td data-row=\"3\" data-col=\"4\">2.776**</td>\n                  <td data-row=\"3\" data-col=\"5\">1.995*</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.229)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.769)</td>\n                  <td data-row=\"4\" data-col=\"4\">(0.847)</td>\n                  <td data-row=\"4\" data-col=\"5\">(0.776)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">price</td>\n                  <td data-row=\"5\" data-col=\"2\"></td>\n                  <td data-row=\"5\" data-col=\"3\">-27.653***</td>\n                  <td data-row=\"5\" data-col=\"4\">-25.968***</td>\n                  <td data-row=\"5\" data-col=\"5\">-23.743***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\"></td>\n                  <td data-row=\"6\" data-col=\"3\">(5.438)</td>\n                  <td data-row=\"6\" data-col=\"4\">(6.212)</td>\n                  <td data-row=\"6\" data-col=\"5\">(5.429)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">price_liquor</td>\n                  <td data-row=\"7\" data-col=\"2\"></td>\n                  <td data-row=\"7\" data-col=\"3\"></td>\n                  <td data-row=\"7\" data-col=\"4\">-2.611</td>\n                  <td data-row=\"7\" data-col=\"5\">-4.077</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\"></td>\n                  <td data-row=\"8\" data-col=\"3\"></td>\n                  <td data-row=\"8\" data-col=\"4\">(4.457)</td>\n                  <td data-row=\"8\" data-col=\"5\">(3.890)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">price_other</td>\n                  <td data-row=\"9\" data-col=\"2\"></td>\n                  <td data-row=\"9\" data-col=\"3\"></td>\n                  <td data-row=\"9\" data-col=\"4\"></td>\n                  <td data-row=\"9\" data-col=\"5\">12.924**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\"></td>\n                  <td data-row=\"10\" data-col=\"3\"></td>\n                  <td data-row=\"10\" data-col=\"4\"></td>\n                  <td data-row=\"10\" data-col=\"5\">(4.164)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"11\" data-col=\"2\">30</td>\n                  <td data-row=\"11\" data-col=\"3\">30</td>\n                  <td data-row=\"11\" data-col=\"4\">30</td>\n                  <td data-row=\"11\" data-col=\"5\">30</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">R2</td>\n                  <td data-row=\"12\" data-col=\"2\">0.511</td>\n                  <td data-row=\"12\" data-col=\"3\">0.750</td>\n                  <td data-row=\"12\" data-col=\"4\">0.754</td>\n                  <td data-row=\"12\" data-col=\"5\">0.822</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\nThis example shows how omitted variable bias can lead to completely **wrong business conclusions**:\n\n- **Wrong conclusion** (simple model): \"Higher-income customers drink less beer - target low-income segments\"\n- **Correct conclusion** (multiple model): \"Higher-income customers drink more beer, but they're price-sensitive - consider premium pricing strategies\"\n\nThe simple regression result could lead to disastrous policy decisions!\n\n# Model Diagnostics\n\nGood regression analysis doesn't stop at fitting the model. We need to check our assumptions and test how good the model explains the dependent variable.\n\n## The explanatory power: $R^2$\n\n$R^2$ measures the proportion of variation in the dependent variable explained by our model.\n\nIt is defined as the ratio between the total variation ('Total Sum of Squares') and\nthe explained variation. Since the residuals are our measure for *unexplained* variation,\nwe can compute $R^2$ by the following formula:\n\n$$R^2 = 1- \\frac{RSS}{TSS}$$\n\nLet's calculate it manually to understand what it means.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get the actual and fitted values\ny_actual <- marketing_data$sales_revenue\ny_fitted <- predict(model_simple)\ny_mean <- mean(y_actual)\n\n# Calculate the components\nTSS <- sum((y_actual - y_mean)^2)      # Total Sum of Squares\nRSS <- sum((y_actual - y_fitted)^2)    # Residual Sum of Squares\n\n# Calculate R²\nr_squared_manual <- 1 - (RSS / TSS)\n\ncat(\"Manual R² calculation:\", round(r_squared_manual, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nManual R² calculation: 0.9351 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"R's built-in R²:\", round(summary(model_simple)$r.squared, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR's built-in R²: 0.9351 \n```\n\n\n:::\n:::\n\n\nBut in practice there is no need to compute it manually, as it is stored in the\n`summary` of every regression object:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compare R² between models\nr2_simple <- summary(model_simple)$r.squared\nr2_multiple <- summary(model_multiple)$r.squared\n\ncat(\"Simple model R²:\", round(r2_simple, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple model R²: 0.9351 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Multiple model R²:\", round(r2_multiple, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMultiple model R²: 0.9437 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Improvement:\", round(r2_multiple - r2_simple, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImprovement: 0.0085 \n```\n\n\n:::\n:::\n\n\nIn our case:\n\n- The $R^2$ of the simple model is 0.9351. This means that this model explains 0.94 % of the variation in the dependent variable.\n- The $R^2$ of the multiple model is 0.9437. This means that this model explains 0.94 % of the variation in the dependent variable.\n\nBut be careful: a higher $R^2$ does not necessarily imply better prediction or inference capability of the model!\n\n## Key Diagnostic Plots\n\nThe most important assumptions of linear regression are about the nature of the error term $\\epsilon$.\nBut as discussed previously, the error term is located on the population level,\nmeaning it will always remain unobservable. Therefore, we usually inspect its sample equivalent, the residuals, to test the most important assumptions.\n\nThe two most important assumptions are:\n\n1. The error term is uncorrelated with the dependent variable.\n2. The error follows a normal distribution with mean zero.\n\nTo test assumption 1, we can look at the correlation between residuals and fitted values.\nIf our model is good, we should see no structure.\n\nTo test assumption 2, we can look at a so called QQ-plot.\nQQ stands for quantile-quantile. Such a plot plots the quantiles of the data\n(here: residuals) against the theoretical quantiles if the data was following a normal distribution.\nIf the residuals are normally distributed, they should follow a straight line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create augmented data with fitted values and residuals\nmarketing_augmented <- augment(model_multiple)\n\n# Tukey-Anscombe Plot (Residuals vs Fitted)\np1 <- ggplot(marketing_augmented, aes(x = .fitted, y = .resid)) +\n  geom_point(alpha = 0.7) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  geom_smooth(se = FALSE, color = \"blue\") +\n  labs(\n    title = \"Residuals vs Fitted Values\",\n    x = \"Fitted Values\",\n    y = \"Residuals\",\n    subtitle = \"Should show no clear pattern\"\n  ) +\n  theme_minimal()\n\n# Normal Q-Q Plot\np2 <- ggplot(marketing_augmented, aes(sample = .resid)) +\n  stat_qq() +\n  stat_qq_line(color = \"red\") +\n  labs(\n    title = \"Normal Q-Q Plot\",\n    subtitle = \"Points should follow the red line\"\n  ) +\n  theme_minimal()\n\ngridExtra::grid.arrange(p1, p2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](linear-regression-r_files/figure-html/diagnostics-1.png){width=672}\n:::\n:::\n\n\nIn this example we see that both assumptions seem to be satisfied, although some\nsmall structure in the residuals persist.\n\n# Data Transformation for Non-linear Relationships\n\nNot all relationships are linear!\nBut remember that for linear regression, we only need to assume\n*linearity in parameters*!\nThis means that sometimes we can transform our data to make initially non-linear relationships linear and still use linear regression effectively.\n\n## When to Transform Data\n\nCommon scenarios requiring transformation:\n\n- **Exponential relationships**: Often seen with salary/experience, population growth\n- **U-shaped relationships**: Common in economics (e.g., effort vs performance)\n- **Diminishing returns**: Sales response to advertising often follows this pattern\n\nIn practice, always visualize your data first and experiment with various transformation strategies - this is the best way to determine whether data transformation can help you.\n\nAlso, the diagnostic plots discussed above can also provide hints on necessary transformations:\nif the Tukey-Anscombe plot shows structure, think about transforming the data!\n\n## Log Transformation Example\n\nLet's examine a **company's revenue growth over time** - a classic example of exponential growth that appears linear after log transformation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First, visualize the raw exponential relationship\nggplot(firm_growth_data, aes(x = year, y = revenue)) +\n  geom_point(size = 2, alpha = 0.8) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"red\", linewidth = 1) +\n  geom_smooth(method = \"loess\", se = FALSE, color = \"blue\", linewidth = 1) +\n  labs(\n    title = \"Company Revenue Growth Over Time (Raw Data)\",\n    subtitle = \"Red = Linear fit (clearly inadequate), Blue = Flexible fit\",\n    x = \"Year\",\n    y = \"Revenue (EUR)\",\n    caption = \"Notice how the linear fit completely misses the exponential pattern\"\n  ) +\n  scale_y_continuous(labels = scales::comma) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](linear-regression-r_files/figure-html/log-transformation-setup-1.png){width=672}\n:::\n:::\n\n\nThe exponential pattern is very clear! The red linear line completely fails to capture the relationship. Let's try a log transformation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create log-transformed variable\nfirm_growth_data_log <- firm_growth_data %>%\n  mutate(log_revenue = log(revenue))\n\n# Fit both models\nmodel_linear_exp <- lm(revenue ~ year, data = firm_growth_data)\nmodel_log_exp <- lm(log_revenue ~ year, data = firm_growth_data_log)\n\n# Visualize the log-transformed relationship\nggplot(firm_growth_data_log, aes(x = year, y = log_revenue)) +\n  geom_point(size = 2, alpha = 0.8) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"blue\", linewidth = 1) +\n  labs(\n    title = \"Log(Revenue) vs Year\",\n    subtitle = \"Perfect linear relationship after transformation!\",\n    x = \"Year\",\n    y = \"Log(Revenue)\",\n    caption = \"The transformation successfully linearizes the exponential relationship\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](linear-regression-r_files/figure-html/log-transformation-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary::modelsummary(\n  models = list(\"Lin-Lin\"=model_linear_exp, \"Log-lin\"=model_log_exp),\n  gof_map = c(\"nobs\", \"r.squared\"),\n  stars = TRUE, output = \"kableExtra\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"NAborder-bottom: 0; width: auto !important; margin-left: auto; margin-right: auto;\" class=\"table\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:center;\"> Lin-Lin </th>\n   <th style=\"text-align:center;\"> Log-lin </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:center;\"> −25037.426* </td>\n   <td style=\"text-align:center;\"> 9.300*** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\"> (10107.611) </td>\n   <td style=\"text-align:center;\"> (0.078) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> year </td>\n   <td style=\"text-align:center;\"> 8991.437*** </td>\n   <td style=\"text-align:center;\"> 0.144*** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;box-shadow: 0px 1.5px\">  </td>\n   <td style=\"text-align:center;box-shadow: 0px 1.5px\"> (843.767) </td>\n   <td style=\"text-align:center;box-shadow: 0px 1.5px\"> (0.007) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Num.Obs. </td>\n   <td style=\"text-align:center;\"> 20 </td>\n   <td style=\"text-align:center;\"> 20 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> R2 </td>\n   <td style=\"text-align:center;\"> 0.863 </td>\n   <td style=\"text-align:center;\"> 0.964 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr></tfoot>\n</table>\n\n`````\n:::\n:::\n\n\n\n### Interpreting Log Models\n\nWhen you transform data, you need to interpret your results accordingly.\nFor instance, when the dependent variable is log-transformed, coefficients represent **percentage changes**:\n\n> Every year is, on average, associated with a\n14.4\n% increase in revenue.\n\n\n::: {.callout-important}\n### Why Log Transformation Works for Exponential Data\n\nExponential relationships have the form: $Y = A \\cdot e^{Bx}$\n\nTaking the natural log: $\\ln(Y) = \\ln(A) + Bx$\n\nThis transforms the exponential curve into a straight line where:\n- The slope B represents the **growth rate**\n- $e^B - 1$ gives the percentage change per unit increase in x\n:::\n\n## Quadratic Relationships\n\nSometimes relationships are U-shaped or inverted-U shaped. A perfect example is **marketing efficiency**: too little spending is inefficient (high fixed costs), and too much spending leads to diminishing returns:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First, visualize the clear U-shaped relationship\nggplot(marketing_efficiency_data, aes(x = marketing_spend, y = cost_per_acquisition)) +\n  geom_point(size = 2, alpha = 0.8, color = \"darkblue\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"red\", linewidth = 1) +\n  geom_smooth(method = \"loess\", se = FALSE, color = \"blue\", linewidth = 1) +\n  labs(\n    title = \"Marketing Efficiency: Cost per Acquisition vs Marketing Spend\",\n    subtitle = \"Red = Linear fit (completely wrong!), Blue = Flexible fit (captures U-shape)\",\n    x = \"Marketing Spend (thousands EUR)\",\n    y = \"Cost per Acquisition (EUR)\",\n    caption = \"Clear U-shaped pattern: optimal spending around 50k EUR\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](linear-regression-r_files/figure-html/exercise-2-1.png){width=672}\n:::\n:::\n\n\nThe U-shaped pattern is unmistakable! Now let's compare linear vs quadratic models:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create squared term for quadratic model\nmarketing_efficiency_data <- marketing_efficiency_data %>%\n  mutate(marketing_spend_squared = marketing_spend^2)\n\n# Fit both models\nmarketing_linear <- lm(cost_per_acquisition ~ marketing_spend, data = marketing_efficiency_data)\nmarketing_quadratic <- lm(cost_per_acquisition ~ marketing_spend + marketing_spend_squared,\n                         data = marketing_efficiency_data)\n\n# Compare R²\nr2_linear_quad <- summary(marketing_linear)$r.squared\nr2_quadratic <- summary(marketing_quadratic)$r.squared\n\ncat(\"Linear model R²:\", round(r2_linear_quad, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear model R²: 0\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nQuadratic model R²:\", round(r2_quadratic, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nQuadratic model R²: 0.999\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nImprovement:\", round(r2_quadratic - r2_linear_quad, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nImprovement: 0.999\n```\n\n\n:::\n:::\n\n\nWith quadratic terms, interpretation becomes more nuanced because the effect of the variable **changes** depending on its current level:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract coefficients for interpretation\nlinear_coef <- coef(marketing_quadratic)[\"marketing_spend\"]\nquadratic_coef <- coef(marketing_quadratic)[\"marketing_spend_squared\"]\n\n# Find the optimal point (minimum of the parabola)\noptimal_spend <- -linear_coef / (2 * quadratic_coef)\ncat(\"Optimal marketing spend:\", round(optimal_spend, 1), \"thousand EUR\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOptimal marketing spend: 50 thousand EUR\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\nUnderstanding Quadratic Models\n\n**The quadratic model equation**: Cost = β₀ + β₁×Spend + β₂×Spend²\n\n**Key insights:**\n\n1. **Linear term** (β₁ = -50.157): The initial direction of the relationship\n2. **Quadratic term** (β₂ = 0.5018): How the slope changes\n   - Positive β₂ → U-shaped (costs increase at extremes)\n   - Negative β₂ → Inverted-U (optimal point in middle)\n3. **Optimal point**: Where marginal effect = 0\n\n:::\n\n# Key Takeaways\n\n## Main Learning Points\n\n1. **Multiple regression** controls for confounding variables and reduces omitted variable bias\n2. **$R^2$** measures explained variance but isn't the only criterion for model quality\n3. **Data transformation** can help linearize non-linear relationships\n4. **geom_smooth(method = \"lm\")** provides easy and effective visualization of regression fits\n5. **Residual analysis** is crucial for checking model assumptions\n6. **Business context** should always guide model interpretation\n7. **Omitted variable bias** can completely reverse coefficient signs and lead to wrong business decisions\n8. **Quadratic models** capture non-linear relationships and reveal optimal points\n\n## Common Pitfalls to Avoid\n\n- Don't interpret correlation as causation\n- Don't ignore potential confounding variables\n- Don't rely solely on $R^2$ for model selection\n- Don't forget to check model assumptions through residual analysis\n- Don't use linear models for clearly non-linear relationships without considering transformations\n- Don't make business decisions based on biased models\n\n## Practice\n\nThe `LinearRegression1` and `LinearRegression2` exercise sets in the `DataScienceExercises` package\ncover the main concepts from this tutorial:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlearnr::run_tutorial(\n  name = \"LinearRegression1\",\n  package = \"DataScienceExercises\",\n  shiny_args = list(\"launch.browser\" = TRUE)\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlearnr::run_tutorial(\n  name = \"LinearRegression2\",\n  package = \"DataScienceExercises\",\n  shiny_args = list(\"launch.browser\" = TRUE)\n)\n```\n:::\n\n\nSee the [blog post on DataScienceExercises](../../blog/2026-06-16-datascienceexercises/index.qmd)\nfor installation instructions.\n\n## Further reading\n\n- [Chapter 5](https://moderndive.com/v2/regression.html) and [Chapter 6](https://moderndive.com/v2/multiple-regression.html) in ModernDive\n\n<script src=\"https://giscus.app/client.js\"\n        data-repo=\"graebnerc/research-methodology-hub\"\n        data-repo-id=\"R_kgDOS7J-4w\"\n        data-category=\"Comments\"\n        data-category-id=\"DIC_kwDOS7J-484C_N51\"\n        data-mapping=\"pathname\"\n        data-strict=\"0\"\n        data-reactions-enabled=\"1\"\n        data-emit-metadata=\"0\"\n        data-input-position=\"bottom\"\n        data-theme=\"preferred_color_scheme\"\n        data-lang=\"en\"\n        crossorigin=\"anonymous\"\n        async>\n</script>\n",
    "supporting": [
      "linear-regression-r_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}