{
  "hash": "22c4664dbad693468da11259b9207740",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hypothesis Testing and Confidence Intervals\"\ndescription: \"Applying sampling theory to make inferences: how to evaluate claims using data (hypothesis testing and p-values) and how to construct ranges of plausible values for population parameters (confidence intervals).\"\nauthor: \"Claudius Gräbner-Radkowitsch\"\ndate: 2026-06-15\ndate-modified: 2026-06-15\nimage: ../../assets/images/placeholder.png\n\nlearning-objectives:\n  - \"Formulate a null and alternative hypothesis for a given research question\"\n  - \"Compute and interpret a test statistic and p-value, and explain what a p-value does and does not mean\"\n  - \"Construct and interpret a confidence interval for a mean and a proportion\"\n  - \"Explain the connection between hypothesis tests and confidence intervals\"\n  - \"Avoid the most common misconceptions about p-values and confidence intervals\"\n\ncategories:\n  - statistics\n  - R\n  - BA\n  - MA\n  - reading\n\nlevel:\n  - BA\n  - MA\n\ncontent-type: reading\n\ncitation:\n  type: entry\n  container-title: \"Methods Hub\"\n  title: \"Hypothesis Testing and Confidence Intervals\"\n  editor:\n    - name: \"Claudius Gräbner-Radkowitsch\"\n  url: https://euf-methodology-hub.netlify.app/resources/statistics/hypothesis-testing-and-confidence-intervals\n---\n\n::: {.callout-note collapse=\"true\"}\n## Part of the Statistics Recap Track\nThis page is the last entry in the [Statistics Recap track](../../tracks/statistics-recap.qmd).\n\n**Previous resource:** [Sampling and Statistical Inference](sampling-and-inference.qmd)\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Packages used for R examples\"}\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggpubr)\n```\n:::\n\n\n\n\n# Two Questions Sampling Theory Can Answer\n\nThe previous ressource on [Sampling and Statistical Inference](sampling-and-inference.qmd) introduced some essential tools for statistical inference: sampling distributions, standard error, and the Central Limit Theorem. In this resource we look on how we can use these tools to quantify the uncertainty associate with the estimates we produce when doing statistical inference.\n\nThere are two types of questions that arise naturally whenever we work with sample data:\n\n**Question 1 — Evaluating a claim:** A company claims that 60% of the balls in your ball pit are white. You draw a sample of 50 and find 70% white. Is the company's claim plausible, or is your sample evidence against it? This is the territory of **hypothesis testing**.\n\n**Question 2 — Constructing a range:** You surveyed 200 customers and found an average spending of €250. You know this is just a sample — the true average for all your customers could be higher or lower. What is a plausible range for that true value? This is the territory of **confidence intervals**.\n\nBoth questions rest on exactly the same foundation: under fairly general conditions, the CLT guarantees that our sample statistic is approximately normally distributed around the true population parameter, with spread equal to the standard error. This fact helps us to conduct hypothesis tests and compute confidence intervals.\n\n# Hypothesis Testing\n\n## The Logic\n\nHypothesis testing is a formal procedure for deciding whether observed data are consistent with a specific claim about the population.\n\nIn this context, the claim we want to evaluate is called the **null hypothesis** $H_0$. It often states \"nothing interesting is happening\" or asserts a specific value for the population parameter. The **alternative hypothesis** $H_1$ states what we would conclude if the null was wrong.\n\nThe key question is: *if $H_0$ were true, how likely would we be to observe a result at least as extreme as what we actually observed?*. \nThis probability is the **p-value**. A small p-value means our observed data would be very unusual under $H_0$ — which we can take as evidence against $H_0$. If, on the other hand, we have a high p-value that means that the data we observe was very likely when the $H_0$ would be true - so it is treated as evidence against rejecting $H_0$.\n\n## A Worked Example: Customer Satisfaction\n\nA company claims its product achieves an average customer satisfaction of 8.0 out of 10. \nTo test whether this claim is plausible, you survey 100 randomly selected customers and find:\n\n- Sample mean satisfaction: $\\bar{x} = 7.5$\n- Sample standard deviation: $s = 1.2$\n\nShould you treat this result as evidence for or against the company's claim?\n\n**Step 1: State the hypotheses.**\n\nIn a first step we need to state our hypotheses explicitly. \nOften this naturally follows from our research question.\nIn the present case, $H_0$ corresponds to the claim of the company:\n\n$$H_0: \\mu = 8.0 \\quad \\text{(company's claim)}$$\nThe alternative would be that the claim of the company was wrong:\n\n$$H_1: \\mu \\neq 8.0 \\quad \\text{(two-sided: could be higher or lower)}$$\n\nHere we speak of a two-sided alternative as the claim could be wrong in two ways: \nthe true satisfaction could be smaller or larger. You do not need to formulate your hypothesis using equalities only. \nYou could, for instance, also check $H_0: \\mu > 8.0$. Then $H_1$ would naturally follow as $H_1: \\mu \\leq 8.0$.\n\n**Step 2: Compute the standard error and test statistic.**\n\nBy the CLT, the sample mean $\\bar{x}$ follows a normal distribution centred at the true $\\mu$ with standard error $SE = s/\\sqrt{n}$:\n\n$$SE = \\frac{1.2}{\\sqrt{100}} = 0.12$$\n\nThe **test statistic** measures how many standard errors our observed mean is from the null hypothesis value:\n\n$$t = \\frac{\\bar{x} - \\mu_0}{SE} = \\frac{7.5 - 8.0}{0.12} = \\frac{-0.5}{0.12} \\approx -4.17$$\n\n**Step 3: Compute the p-value.**\n\nThe p-value is the probability of observing a test statistic at least as extreme as $-4.17$ (in either direction) if $H_0$ was true.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Manual hypothesis test and R's t.test()\"}\n# Sample data (summarised)\nn      <- 100\nx_bar  <- 7.5\ns      <- 1.2\nmu_0   <- 8.0\n\n# Standard error and test statistic\nse     <- s / sqrt(n)\nt_stat <- (x_bar - mu_0) / se\n\n# p-value (two-tailed, using t-distribution with df = n - 1)\np_val  <- 2 * pt(abs(t_stat), df = n - 1, lower.tail = FALSE)\n\ncat(\"Test statistic t =\", round(t_stat, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTest statistic t = -4.167 \n```\n\n\n:::\n\n```{.r .cell-code  code-summary=\"Manual hypothesis test and R's t.test()\"}\ncat(\"p-value =\", round(p_val, 6), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value = 6.6e-05 \n```\n\n\n:::\n\n```{.r .cell-code  code-summary=\"Manual hypothesis test and R's t.test()\"}\n# R's built-in t.test() gives the same result\n# (requires the raw data; here we use a simulation to illustrate)\nset.seed(42)\nscores <- rnorm(n, mean = x_bar, sd = s)   # simulated sample matching our summary stats\nt_test <- t.test(scores, mu = mu_0, alternative = \"two.sided\")\nt_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  scores\nt = -3.689, df = 99, p-value = 0.0003681\nalternative hypothesis: true mean is not equal to 8\n95 percent confidence interval:\n 7.291064 7.786971\nsample estimates:\nmean of x \n 7.539018 \n```\n\n\n:::\n:::\n\n\nThis p-value is tiny: it says that if $H_0$ was true, the probability to get the sample we got is essentially zero per cent.\nSince we got this sample, this is considered strong evidence against $H_0$ and, therefore, the company's claim.\nFor a visualization of this test see @fig-ht.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Visualizing the hypothesis test\"}\nx_range <- seq(7.2, 8.8, length.out = 500)\ndf_curve <- tibble(x = x_range, y = dnorm(x_range, mean = mu_0, sd = se))\n\ncrit_val <- qnorm(0.025, mean = mu_0, sd = se)  # lower critical value\n\nggplot(df_curve, aes(x = x, y = y)) +\n  geom_line(linewidth = 1.2, color = \"#3498db\") +\n  geom_area(data = filter(df_curve, x <= mu_0 - abs(x_bar - mu_0)),\n    fill = \"#e74c3c\", alpha = 0.4) +\n  geom_area(data = filter(df_curve, x >= mu_0 + abs(x_bar - mu_0)),\n    fill = \"#e74c3c\", alpha = 0.4) +\n  geom_vline(xintercept = mu_0, linetype = \"dashed\", color = \"gray50\") +\n  geom_vline(xintercept = x_bar, linetype = \"solid\", color = \"#e74c3c\", linewidth = 1.2) +\n  annotate(\"text\", x = mu_0 + 0.02, y = max(df_curve$y) * 0.95,\n    label = paste0(\"H₀: μ = \", mu_0), hjust = 0, color = \"gray40\", size = 3.5) +\n  annotate(\"text\", x = x_bar - 0.02, y = max(df_curve$y) * 0.5,\n    label = paste0(\"Observed\\nx̄ = \", x_bar), hjust = 1, color = \"#e74c3c\", size = 3.5) +\n  annotate(\"text\", x = 7.35, y = max(df_curve$y) * 0.15,\n    label = paste0(\"p-value ≈ \", round(p_val, 5)), color = \"#e74c3c\", size = 3.5) +\n  labs(\n    title = \"Hypothesis Test: Is Average Satisfaction 8.0?\",\n    subtitle = \"Sampling distribution of x̄ under H₀: μ = 8.0 | Red line = observed x̄ = 7.5\",\n    x = \"Sample Mean\", y = \"Probability Density\"\n  ) +\n  theme_minimal() +\n  theme(panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![The hypothesis test. The normal curve shows the sampling distribution of the sample mean **if** the null hypothesis were true (μ₀ = 8.0). Our observed mean of 7.5 falls 4.17 standard errors from the null — in the extreme left tail. The red shaded areas show the p-value: the probability of observing a result this extreme or more extreme under H₀.](hypothesis-testing-and-confidence-intervals_files/figure-html/fig-ht-1.png){#fig-ht width=672}\n:::\n:::\n\n\n## The Decision Rule\n\nBefore seeing the data, researchers choose a **significance level** $\\alpha$ — typically 0.05 — as the threshold for rejecting $H_0$. If $p\\text{-value} \\leq \\alpha$, we reject $H_0$. If $p\\text{-value} > \\alpha$, we fail to reject $H_0$ (we do not \"accept\" it — absence of evidence is not evidence of absence).\n\nThis decision rule leads to two types of errors:\n\n| | $H_0$ is actually true | $H_0$ is actually false |\n|---|---|---|\n| We reject $H_0$ | **Type I error** (false positive, rate = $\\alpha$) | Correct |\n| We fail to reject $H_0$ | Correct | **Type II error** (false negative) |\n\nBy setting $\\alpha = 0.05$, we accept a 5% probability of incorrectly rejecting a true null hypothesis.\nNote that this value is a _convention_. There is no mathematical law that prescribes it and you could, in principle, also choose different values for $\\alpha$. Just keep in mind the associated trade-off between power and the Type I error rate.\n\nThe **power** of a test is the probability of correctly rejecting a false null hypothesis — detecting a real effect when it actually exists. It equals $1 - P(\\text{Type II error}) = 1 - \\beta$. When we lower $\\alpha$ (say, from 0.05 to 0.01) to reduce the risk of a false positive, the critical threshold shifts, making it harder to reject $H_0$ even when $H_1$ is true — and power falls. Conversely, raising $\\alpha$ increases power but at the cost of more false positives. The only way to reduce both error types simultaneously is to increase the sample size, which narrows the sampling distributions of both $H_0$ and $H_1$.\n\n@fig-power illustrates this trade-off for the customer satisfaction example, assuming a realistic alternative of $\\mu_1 = 7.8$ (a real but modest shortfall from the claimed 8.0). @tbl-power shows the corresponding numbers for three choices of $\\alpha$.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Power vs. Type I error trade-off\"}\nmu_0  <- 8.0\nmu_1  <- 7.8   # assumed true alternative\nse_ht <- 0.12  # SE from the example (s=1.2, n=100)\n\nalpha_show <- 0.05\ncv <- qnorm(alpha_show, mean = mu_0, sd = se_ht)  # one-sided lower critical value\n\nx_seq  <- seq(7.3, 8.6, length.out = 600)\ndf_two <- tibble(\n  x  = x_seq,\n  h0 = dnorm(x_seq, mu_0, se_ht),\n  h1 = dnorm(x_seq, mu_1, se_ht)\n)\n\nggplot(df_two, aes(x = x)) +\n  # α region: left tail of H₀ past CV\n  geom_area(data = filter(df_two, x <= cv),\n    aes(y = h0), fill = \"#e74c3c\", alpha = 0.4) +\n  # β region: right tail of H₁ past CV (missed detections)\n  geom_area(data = filter(df_two, x >= cv),\n    aes(y = h1), fill = \"#e67e22\", alpha = 0.4) +\n  # Power region: left tail of H₁ below CV\n  geom_area(data = filter(df_two, x <= cv),\n    aes(y = h1), fill = \"#27ae60\", alpha = 0.4) +\n  # Distribution curves\n  geom_line(aes(y = h0, color = \"H₀: μ = 8.0\"), linewidth = 1.2) +\n  geom_line(aes(y = h1, color = \"H₁: μ = 7.8\"), linewidth = 1.2) +\n  # Critical value\n  geom_vline(xintercept = cv, linetype = \"dashed\", linewidth = 1, color = \"black\") +\n  # Labels\n  annotate(\"text\", x = cv - 0.06, y = 1.0,\n    label = paste0(\"CV = \", round(cv, 3), \"\\n(α = \", alpha_show, \")\"),\n    hjust = 1, size = 3.2, color = \"black\") +\n  annotate(\"text\", x = 7.55, y = 0.5,\n    label = paste0(\"α = \", alpha_show, \"\\n(Type I error)\"),\n    hjust = 0.5, size = 3, color = \"#e74c3c\", fontface = \"bold\") +\n  annotate(\"text\", x = 8.25, y = 0.5,\n    label = paste0(\"β ≈ \", round(1 - pnorm(cv, mu_1, se_ht), 2), \"\\n(Type II error)\"),\n    hjust = 0.5, size = 3, color = \"#e67e22\", fontface = \"bold\") +\n  annotate(\"text\", x = 7.67, y = 2.2,\n    label = paste0(\"Power ≈ \", round(pnorm(cv, mu_1, se_ht), 2)),\n    hjust = 0.5, size = 3, color = \"#27ae60\", fontface = \"bold\") +\n  scale_color_manual(\n    values = c(\"H₀: μ = 8.0\" = \"#3498db\", \"H₁: μ = 7.8\" = \"#27ae60\"),\n    name = NULL) +\n  labs(\n    title = \"Power vs. Type I Error: The Fundamental Trade-off\",\n    subtitle = paste0(\"One-sided test | SE = \", se_ht,\n      \" | True alternative μ₁ = \", mu_1),\n    x = \"Sample Mean\", y = \"Probability Density\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\", panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![The power–α trade-off. The blue curve is the sampling distribution of x̄ under H₀ (μ = 8.0); the green curve shows the distribution under a plausible true alternative (μ₁ = 7.8). The dashed vertical line is the critical value for α = 0.05. The red area is α (rejecting a true H₀); the orange area is β (failing to reject when H₁ is true); the green area is power (correctly rejecting H₀). Moving the critical value left reduces α but shrinks the green area — power falls.](hypothesis-testing-and-confidence-intervals_files/figure-html/fig-power-1.png){#fig-power width=672}\n:::\n:::\n\n\n\n::: {#tbl-power .cell tbl-cap='How the choice of α determines the trade-off between Type I error rate and power, for a one-sided test with SE = 0.12 and a true alternative of μ₁ = 7.8.'}\n\n```{.r .cell-code  code-summary=\"Power table for different α levels\"}\nalphas_tbl <- c(0.10, 0.05, 0.01)\ncvs_tbl    <- qnorm(alphas_tbl, mean = mu_0, sd = se_ht)\npowers_tbl <- pnorm(cvs_tbl,   mean = mu_1, sd = se_ht)\n\npower_table <- tibble(\n  `α (significance level)`   = alphas_tbl,\n  `Critical value`            = round(cvs_tbl, 3),\n  `Power (1 − β)`             = round(powers_tbl, 3),\n  `Type II error rate (β)`    = round(1 - powers_tbl, 3)\n)\n\nknitr::kable(power_table)\n```\n\n::: {.cell-output-display}\n\n\n| α (significance level)| Critical value| Power (1 − β)| Type II error rate (β)|\n|----------------------:|--------------:|-------------:|----------------------:|\n|                   0.10|          7.846|         0.650|                  0.350|\n|                   0.05|          7.803|         0.509|                  0.491|\n|                   0.01|          7.721|         0.255|                  0.745|\n\n\n:::\n:::\n\n\nThe table confirms the intuition from @fig-power: a stricter $\\alpha$ (0.01 instead of 0.05) reduces false positives but cuts power nearly in half. The choice of $\\alpha$ is therefore not a mechanical decision — it reflects a deliberate judgement about which type of error is more costly in your specific context. And the common value of $\\alpha=0.05$ is exactly that: a more or less deliberate choice that has become a convention.\n\n# Understanding p-values\n\nThe p-value is one of the most commonly misunderstood quantities in statistics. Getting it right matters.\n\n**What a p-value IS:**\n\n> The probability of observing a test statistic at least as extreme as the one we computed, *assuming the null hypothesis is true*.\n\n**What a p-value IS NOT:**\n\n- ✗ The probability that $H_0$ is true\n- ✗ The probability that we made a mistake\n- ✗ A measure of the size or practical importance of an effect\n- ✗ Evidence that the alternative hypothesis is true\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Demonstrating what a p-value is via simulation\"}\nset.seed(42)\nn_sim <- 10000\nsim_tstats <- replicate(n_sim, {\n  sim_sample <- rnorm(n, mean = mu_0, sd = s)\n  (mean(sim_sample) - mu_0) / (sd(sim_sample) / sqrt(n))\n})\n\nsim_p <- mean(abs(sim_tstats) >= abs(t_stat))\n\nggplot(tibble(t = sim_tstats), aes(x = t)) +\n  geom_histogram(aes(fill = abs(t) >= abs(t_stat)), bins = 80,\n    color = \"white\", alpha = 0.85) +\n  scale_fill_manual(values = c(\"FALSE\" = \"#3498db\", \"TRUE\" = \"#e74c3c\"),\n    labels = c(\"FALSE\" = \"Less extreme than observed\",\n               \"TRUE\" = paste0(\"At least as extreme (\", round(sim_p * 100, 3), \"%)\")),\n    name = NULL) +\n  geom_vline(xintercept = c(-abs(t_stat), abs(t_stat)),\n    linetype = \"dashed\", color = \"#e74c3c\", linewidth = 1) +\n  labs(\n    title = \"What the p-value means: simulation under H₀\",\n    subtitle = paste0(\"10,000 samples drawn assuming μ = 8.0 | \",\n      round(sim_p * 100, 3), \"% produce |t| ≥ \", round(abs(t_stat), 2)),\n    x = \"Test Statistic t\", y = \"Count\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\", panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![Simulating what the p-value means. We draw 10,000 samples from a population where H₀ is true (μ = 8.0), compute the test statistic for each, and record the proportion that are at least as extreme as our observed t = -4.17. That proportion is the p-value.](hypothesis-testing-and-confidence-intervals_files/figure-html/fig-pval-sim-1.png){#fig-pval-sim width=672}\n:::\n:::\n\n\nA small p-value tells you that your data are unlikely *under the assumption that $H_0$ is true*. It says nothing about whether $H_0$ is likely to be true in the first place.\n\n::: {.callout-note .level-advanced}\n## MA / PhD\n\nAt MA/PhD level, two further issues deserve attention.\n\n**Statistical vs. practical significance.** With large samples, even trivially small differences become statistically significant. A satisfaction score of 7.99 vs. 8.00 might yield p < 0.05 with n = 100,000. Always ask: is the effect large enough to matter? Complement p-values with effect sizes (Cohen's d, odds ratios) and confidence intervals.\n\n**The multiple comparisons problem.** If you test 20 hypotheses at α = 0.05, you expect about one false rejection by chance alone. Corrections such as Bonferroni or Benjamini–Hochberg control the family-wise error rate or false discovery rate when testing many hypotheses simultaneously.\n:::\n\n# Confidence Intervals\n\n## The Logic\n\nA **confidence interval** (CI) is a range of plausible values for the population parameter, constructed from the sample data. Rather than committing to a single point estimate, a CI gives a plausible range for the true value.\nBy doing so, it also communicates the *precision* of our estimate: larger CI indicate greater uncertainty and vice versa.\n\nA 95% confidence interval is constructed so that **if we repeated the sampling procedure many times, 95% of the resulting intervals would contain the true population parameter.**\n\nThis is subtler than it sounds — and easy to get wrong (see below).\n\n## Constructing a Confidence Interval\n\nFor large samples, the CLT guarantees that our estimator is approximately normally distributed. A 95% CI for a mean is:\n\n$$\\bar{x} \\pm z^* \\cdot SE$$\n\nwhere $z^* = 1.96$ is the 97.5th percentile of the standard normal (so that 95% of the distribution lies between $-1.96$ and $+1.96$), and $SE = s/\\sqrt{n}$.^[There are also other ways to construct a CI, which do not rely on the assumption of normally distributed estimators. But their treatment is beyond the scope of this resource.]\n\n## Example: Ball Pit\n\nReturning to our ball pit: we draw 100 balls and find that 68 are white ($\\hat{p} = 0.68$). We now want to construct a 95% CI for the true proportion of white balls.\n\n**Step 1: Compute the standard error.**\n\nThe standard error for a proportion is $SE = \\sqrt{\\hat{p}(1-\\hat{p})/n}$. With our numbers:\n\n$$SE = \\sqrt{\\frac{0.68 \\times 0.32}{100}} = \\sqrt{0.002176} \\approx 0.0466$$\n\n**Step 2: Use the CLT to derive the interval.**\n\nBy the CLT, $\\hat{p}$ is approximately normally distributed around the true $p$. This means that in 95% of samples, $\\hat{p}$ will fall within $\\pm 1.96 \\cdot SE$ of the true value:\n\n$$P\\!\\left(p - 1.96 \\cdot SE \\;\\leq\\; \\hat{p} \\;\\leq\\; p + 1.96 \\cdot SE\\right) = 0.95$$\n\nRearranging this inequality — subtracting $\\hat{p}$ from all parts and multiplying by $-1$ — gives an equivalent statement with $p$ in the centre:\n\n$$P\\!\\left(\\hat{p} - 1.96 \\cdot SE \\;\\leq\\; p \\;\\leq\\; \\hat{p} + 1.96 \\cdot SE\\right) = 0.95$$\n\nThis is the confidence interval. The rearrangement is the key step: we flip from \"the estimate is within 1.96 SEs of the truth\" to \"the truth is within 1.96 SEs of the estimate.\" This works because the ±1.96 SE relationship is symmetric.\n\n**Step 3: Plug in the numbers.**\n\n$$\\text{Margin of error} = 1.96 \\times 0.0466 \\approx 0.091$$\n\n$$95\\%\\text{ CI} = [0.68 - 0.091,\\; 0.68 + 0.091] = [0.589,\\; 0.771]$$\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Constructing a 95% confidence interval for a proportion\"}\nn_balls   <- 100\nn_white   <- 68\np_hat     <- n_white / n_balls\n\nse_prop   <- sqrt(p_hat * (1 - p_hat) / n_balls)\nz_star    <- qnorm(0.975)   # = 1.96\n\nci_lower  <- p_hat - z_star * se_prop\nci_upper  <- p_hat + z_star * se_prop\n\ncat(\"Point estimate: p̂ =\", p_hat, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPoint estimate: p̂ = 0.68 \n```\n\n\n:::\n\n```{.r .cell-code  code-summary=\"Constructing a 95% confidence interval for a proportion\"}\ncat(\"Standard error: SE =\", round(se_prop, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStandard error: SE = 0.0466 \n```\n\n\n:::\n\n```{.r .cell-code  code-summary=\"Constructing a 95% confidence interval for a proportion\"}\ncat(\"95% CI: [\", round(ci_lower, 3), \",\", round(ci_upper, 3), \"]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: [ 0.589 , 0.771 ]\n```\n\n\n:::\n\n```{.r .cell-code  code-summary=\"Constructing a 95% confidence interval for a proportion\"}\n# R's built-in function\nprop.test(x = n_white, n = n_balls, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  n_white out of n_balls, null probability 0.5\nX-squared = 12.25, df = 1, p-value = 0.0004653\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5782080 0.7677615\nsample estimates:\n   p \n0.68 \n```\n\n\n:::\n:::\n\n\nOur 95% CI is [0.589, 0.771]. This is the range of values for the true proportion $p$ that are consistent with what we observed in our sample.\n\n::: {.callout-tip}\n## CIs without the normality assumption\n\nThe interval above rests on the CLT: it works well when $n$ is large enough that $\\hat{p}$ is approximately normal. Two alternatives exist when that assumption is in doubt.\n\n**Exact binomial CI.** For proportions specifically, R's `binom.test()` constructs an interval directly from the binomial distribution, with no normal approximation involved. It is more accurate when $n$ is small or when $p$ is close to 0 or 1 (where the normal approximation distorts the tails).\n\n```r\nbinom.test(x = 68, n = 100, conf.level = 0.95)\n```\n\n**Bootstrap CI.** The most general approach: resample your data with replacement many times, compute the statistic on each resample, and use the 2.5th and 97.5th percentiles of that distribution directly as the CI boundaries. No distributional assumption required. In R, the `boot` package provides a standard implementation, or you can build a simple version yourself using `replicate()` and `sample()` — the same tools used for Monte Carlo simulations on the previous page.\n\nBootstrap CIs are particularly valuable when your statistic is not a mean or proportion (e.g., a median, a correlation, or a regression coefficient in a small sample) and the CLT approximation is unreliable.\n:::\n\n## The Correct Interpretation\n\nYou will often here a statement similar to \"there is a 95% probability that the true proportion lies in [0.589, 0.771]\". \nThis is **wrong**! The true proportion is a fixed (though unknown) number — it is either in the interval or it isn't. Probability does not apply to a fixed value.\n\nThe correct statement is: **we used a procedure that generates correct intervals 95% of the time.** In any specific interval, we cannot say with certainty whether the true value is inside or outside — but we trust our procedure.\nThis is illustrated in @fig-ci-coverage.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Visualizing 95% confidence: many CIs from the same population\"}\nset.seed(99)\ntrue_p   <- 0.65\nN        <- 5000\npop      <- sample(c(\"White\", \"Grey\"), N, replace = TRUE,\n                   prob = c(true_p, 1 - true_p))\nn_ci     <- 50\nn_trials <- 100\n\nci_results <- bind_rows(lapply(seq_len(n_trials), function(i) {\n  s     <- sample(pop, n_ci, replace = FALSE)\n  ph    <- mean(s == \"White\")\n  se_i  <- sqrt(ph * (1 - ph) / n_ci)\n  tibble(\n    trial = i,\n    p_hat = ph,\n    lower = ph - 1.96 * se_i,\n    upper = ph + 1.96 * se_i,\n    covers = (ph - 1.96 * se_i <= true_p) & (ph + 1.96 * se_i >= true_p)\n  )\n}))\n\ncoverage_pct <- round(mean(ci_results$covers) * 100, 1)\n\nggplot(ci_results, aes(y = trial, x = p_hat, color = covers)) +\n  geom_point(size = 1.5) +\n  geom_errorbarh(aes(xmin = lower, xmax = upper), height = 0, linewidth = 0.6) +\n  geom_vline(xintercept = true_p, linetype = \"dashed\", color = \"black\", linewidth = 1) +\n  scale_color_manual(values = c(\"TRUE\" = \"grey50\", \"FALSE\" = \"#e74c3c\"),\n    labels = c(\"TRUE\" = \"Contains true p\", \"FALSE\" = \"Does not contain true p\"),\n    name = NULL) +\n  scale_x_continuous(labels = scales::percent_format(), limits = c(0.25, 1.05)) +\n  annotate(\"text\", x = 0.66, y = n_trials * 1.02,\n    label = paste0(\"Coverage: \", coverage_pct, \"% of intervals contain true p\"),\n    hjust = 0, size = 3.5) +\n  labs(\n    title = \"95% Confidence Intervals from 100 Different Samples\",\n    subtitle = paste0(\"Each interval: n = \", n_ci, \" balls | True p = 65% (dashed) | Red = intervals that miss\"),\n    x = \"Estimated Proportion of White Balls\", y = \"Sample Number\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\", panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![100 confidence intervals, each constructed from a different sample of 50 balls from the same ball pit (true p = 0.65, dashed line). About 95 of the 100 intervals contain the true proportion (grey). The red intervals are the roughly 5% that miss — not because we did anything wrong, but because that is the expected behaviour of a 95% procedure.](hypothesis-testing-and-confidence-intervals_files/figure-html/fig-ci-coverage-1.png){#fig-ci-coverage width=672}\n:::\n:::\n\n\n## The Effect of Sample Size on CI Width\n\nWider CIs reflect more uncertainty. Narrower CIs reflect more precision. \n@fig-ci-width shows: as the standard error shrinks with larger $n$, so does the CI width.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"CI width as a function of sample size\"}\nci_width_df <- bind_rows(lapply(c(20, 50, 100, 200, 500, 1000), function(sn) {\n  ph  <- true_p  # use known true p for illustration\n  se_n <- sqrt(ph * (1 - ph) / sn)\n  tibble(n = sn, width = 2 * 1.96 * se_n)\n}))\n\nggplot(ci_width_df, aes(x = n, y = width)) +\n  geom_line(color = \"#3498db\", linewidth = 1.2) +\n  geom_point(color = \"#3498db\", size = 3) +\n  scale_x_log10(breaks = c(20, 50, 100, 200, 500, 1000)) +\n  scale_y_continuous(labels = scales::percent_format()) +\n  labs(\n    title = \"Width of 95% CI as a Function of Sample Size\",\n    subtitle = \"For proportion p = 0.65 | Note: halving the width requires quadrupling n\",\n    x = \"Sample Size (n)\", y = \"CI Width (percentage points)\"\n  ) +\n  theme_minimal() +\n  theme(panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![Confidence interval width decreases with sample size, but with diminishing returns. Quadrupling the sample size halves the CI width.](hypothesis-testing-and-confidence-intervals_files/figure-html/fig-ci-width-1.png){#fig-ci-width width=672}\n:::\n:::\n\n\n# The Connection Between Hypothesis Tests and Confidence Intervals\n\nHypothesis tests and confidence intervals are two sides of the same coin. For a two-sided test at significance level $\\alpha$:\n\n> **A value $\\mu_0$ is rejected at level $\\alpha$ if and only if $\\mu_0$ lies outside the $(1 - \\alpha)$ confidence interval.**\n\nIn our customer satisfaction example: the 95% CI for $\\mu$ is:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Customer satisfaction CI\"}\nci_sat_lower <- x_bar - qnorm(0.975) * se\nci_sat_upper <- x_bar + qnorm(0.975) * se\n\ncat(\"95% CI for mean satisfaction: [\",\n  round(ci_sat_lower, 3), \",\", round(ci_sat_upper, 3), \"]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for mean satisfaction: [ 7.265 , 7.735 ]\n```\n\n\n:::\n\n```{.r .cell-code  code-summary=\"Customer satisfaction CI\"}\ncat(\"H₀ value (μ₀ = 8.0) inside the CI?\", ci_sat_lower <= mu_0 & mu_0 <= ci_sat_upper)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nH₀ value (μ₀ = 8.0) inside the CI? FALSE\n```\n\n\n:::\n:::\n\n\nThe null value 8.0 falls far outside the 95% CI — consistent with the very small p-value we found earlier.\n\nThis equivalence is useful: a confidence interval conveys everything a hypothesis test does (whether we reject $H_0$) and more (how large the plausible range of values is). This is why many statisticians prefer reporting CIs over p-values alone.\n\n::: {.callout-note .level-advanced}\n## MA / PhD\n\nThe equivalence between tests and CIs holds exactly only when both use the same distributional assumptions. Some common pitfalls:\n\n- A 95% CI based on the normal approximation may not be exactly equivalent to a test based on the exact binomial distribution for small samples.\n- For non-symmetric CIs (e.g., likelihood ratio CIs), the equivalence still holds but the interval may not be centred on the point estimate.\n- Bayesian **credible intervals** look similar to CIs but have a different meaning: a 95% Bayesian credible interval *does* contain the true value with 95% posterior probability, given the prior. This is closer to how most people intuitively interpret CIs — but requires specifying a prior distribution.\n:::\n\n# Common Misconceptions Summarised\n\n| Misconception | Correct statement |\n|---|---|\n| \"p = 0.03 means there is a 3% probability that H₀ is true.\" | The p-value is the probability of observing our data (or more extreme), *given* H₀ is true. It says nothing about the probability H₀ is true. |\n| \"p > 0.05 means we have shown H₀ is true.\" | Failing to reject H₀ only means the data are not inconsistent with H₀. It is not evidence *for* H₀. |\n| \"The 95% CI means there is a 95% chance the true value is in this interval.\" | The true value is fixed (not random). The 95% refers to the procedure: 95% of such intervals cover the true value. |\n| \"A statistically significant result is important.\" | Statistical significance depends on sample size. With large enough samples, trivially small effects become significant. Always consider effect size alongside the p-value. |\n\n::: {.callout-tip}\n## Practice exercises\nTest your understanding with the companion exercise set:\n[Hypothesis Testing and Confidence Intervals: Practice Exercises](hypothesis-testing-exercises.qmd)\n\nSeven exercises covering CI interpretation, p-value reasoning, statistical vs. practical\nsignificance, Type I/II error trade-offs, and step-by-step calculations — with hidden\nsolutions.\n:::\n\n---\n\n**This page ends the statistics recap track.** The tools covered across all six pages — descriptive statistics, probability theory, and the inferential machinery of sampling distributions, hypothesis tests, and confidence intervals — form the conceptual foundation for applied empirical work. The natural next step is applying these ideas within specific methods: regression analysis, experimental design, or survey methodology, all of which are covered in other sections of the [Resource Library](../../resources/index.qmd).\n\n**Track overview:** [A Recap of Undergraduate Statistics](../../tracks/statistics-recap.qmd)\n\n---\n\n# Comments and questions\n\n<script src=\"https://giscus.app/client.js\"\n        data-repo=\"graebnerc/research-methodology-hub\"\n        data-repo-id=\"R_kgDOS7J-4w\"\n        data-category=\"Comments\"\n        data-category-id=\"DIC_kwDOS7J-484C_N51\"\n        data-mapping=\"pathname\"\n        data-strict=\"0\"\n        data-reactions-enabled=\"1\"\n        data-emit-metadata=\"0\"\n        data-input-position=\"bottom\"\n        data-theme=\"preferred_color_scheme\"\n        data-lang=\"en\"\n        crossorigin=\"anonymous\"\n        async>\n</script>\n",
    "supporting": [
      "hypothesis-testing-and-confidence-intervals_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}