{
  "hash": "6208f766a1868857013d029abeefec2e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Experiments in R\"\ndescription: \"How to analyze experimental data in R: t-tests for simple comparisons, one-way and two-way ANOVA for multi-group designs, effect sizes, post-hoc tests, and power analysis.\"\nauthor: \"Claudius Gräbner-Radkowitsch\"\ndate: 2026-06-16\ndate-modified: 2026-06-16\nimage: ../../assets/images/placeholder.png\n\nlearning-objectives:\n  - \"Conduct independent and paired t-tests and calculate Cohen's d effect size\"\n  - \"Run one-way and two-way ANOVA using both `aov()` and `lm()` and explain why they give identical results\"\n  - \"Perform post-hoc comparisons with Tukey's HSD to identify which groups differ\"\n  - \"Conduct a priori and post-hoc power analysis using the pwr package\"\n\ncategories:\n  - R\n  - experiments\n  - statistics\n  - BA\n  - tutorial\n\nlevel:\n  - BA\n\ncontent-type: tutorial\n\ncitation:\n  type: entry\n  container-title: \"Methods Hub\"\n  title: \"Experiments in R\"\n  editor:\n    - name: \"Claudius Gräbner-Radkowitsch\"\n  url: https://euf-methodology-hub.netlify.app/resources/r-programming/experiments-in-r\n---\n\n## Video lecture\n\n```{=html}\n<div class=\"embed-container\">\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube-nocookie.com/embed/videoseries?si=UBJo1AiCblQZFtZD&amp;list=PLZDawQMrG1RImURlbldAF773MDRqeARNu\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>\n</div>\n```\n\n# Introduction\n\nIn this tutorial we will learn how to analyze data obtained from experiments. We will\ncomplement the theoretical treatment by also introducing some additional, practically relevant\nconcepts.\n\nMore precisely, we focus on the following aspects:\n\n- Import and explore datasets as typically produced by experiments\n- Conduct t-tests for simple experimental comparisons\n- Perform ANOVA for multi-group comparisons\n- Understand how ANOVA is a special case of linear regression\n- Analyze factorial experimental designs\n- Calculate and interpret effect sizes\n- Create visualizations of experimental results\n\nThroughout the tutorial we will use the following packages:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)        # Data manipulation\nlibrary(ggplot2)      # Data visualization\nlibrary(ggdist)       # More visualization options\nlibrary(readr)        # Simple data import\nlibrary(broom)        # Extract model data\nlibrary(effectsize)   # Effect size calculations\nlibrary(car)          # Advanced ANOVA functions\nlibrary(emmeans)      # Post-hoc comparisons\nlibrary(knitr)        # For nice tables\nlibrary(kableExtra)   # For enhanced table formatting\nlibrary(patchwork)    # For aligning multiple plots\nlibrary(pwr)          # For power analysis and sample size planning\n```\n:::\n\n\nWe will use the following data sets:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleadership_study_between <- read_csv(\n  file = \"data/leadership_study_between.csv\", show_col_types = FALSE)\nleadership_study_within <- read_csv(\n  file = \"data/leadership_study_within.csv\", show_col_types = FALSE)\ncommunication_study <- read_csv(\n  file = \"data/communication_study.csv\", show_col_types = FALSE)\nfactorial_study <- read_csv(\n  file = \"data/factorial_study.csv\", show_col_types = FALSE)\n```\n:::\n\n\nFor each main analysis tool - t-test, one-way ANOVA, two-way ANOVA - there are\na number of steps to be taken:\n\n1. Get an exploratory overview over the data\n2. Check the assumptions of the analysis tool\n3. Implement the analysis tool\n4. Calculate standardized effect sizes\n5. Conduct post-hoc tests, if necessary\n\nSince the commands are basically the same for all tools, we discuss these steps\nmore extensively in the beginning when dealing with t-tests, and only provide\nexample code later on.\n\n# The data used\n\nAs usual, it is a good idea to start with looking at the data sets, such that you know what the data looks like:\n\n## The between leadership study\n\nResults of an experiment where the treatment group has received leadership training, and the control group did not. Both groups participated in an exercise where their performance was assessed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(leadership_study_between) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| participant_id|group   | team_performance|\n|--------------:|:-------|----------------:|\n|              1|control |         69.39524|\n|              2|control |         72.69823|\n|              3|control |         90.58708|\n|              4|control |         75.70508|\n|              5|control |         76.29288|\n|              6|control |         92.15065|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(leadership_study_between) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|   |participant_id |   group         |team_performance |\n|:--|:--------------|:----------------|:----------------|\n|   |Min.   : 1.00  |Length:60        |Min.   : 55.33   |\n|   |1st Qu.:15.75  |Class :character |1st Qu.: 70.71   |\n|   |Median :30.50  |Mode  :character |Median : 79.33   |\n|   |Mean   :30.50  |NA               |Mean   : 79.16   |\n|   |3rd Qu.:45.25  |NA               |3rd Qu.: 87.32   |\n|   |Max.   :60.00  |NA               |Max.   :103.69   |\n\n\n:::\n:::\n\n\n## The within leadership study\n\nThe effectiveness of a leadership training was assessed by testing the performance of a group before and after the training.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(leadership_study_within) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| participant_id| pre_performance| post_performance|\n|--------------:|---------------:|----------------:|\n|             31|        77.94803|         86.26464|\n|             32|        74.38718|         79.04929|\n|             33|        71.90985|         90.95126|\n|             34|        64.97675|         90.78133|\n|             35|        80.88522|         90.21581|\n|             36|        65.19792|         88.88640|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(leadership_study_within) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|   |participant_id |pre_performance |post_performance |\n|:--|:--------------|:---------------|:----------------|\n|   |Min.   :31.00  |Min.   :56.66   |Min.   : 66.51   |\n|   |1st Qu.:38.25  |1st Qu.:64.46   |1st Qu.: 78.97   |\n|   |Median :45.50  |Median :68.07   |Median : 82.48   |\n|   |Mean   :45.50  |Mean   :69.25   |Mean   : 83.78   |\n|   |3rd Qu.:52.75  |3rd Qu.:73.72   |3rd Qu.: 89.57   |\n|   |Max.   :60.00  |Max.   :87.50   |Max.   :103.69   |\n\n\n:::\n:::\n\n\n## The communication study\n\nAn experiment where employees communicated only by one of three possible ways\n(face_to_face, via video calls or via email) and then their work satisfaction was\nassessed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(communication_study) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| participant_id|communication_method | satisfaction_score| task_completion_time|\n|--------------:|:--------------------|------------------:|--------------------:|\n|              1|face_to_face         |           5.587774|             22.63382|\n|              2|face_to_face         |           7.946131|             21.65397|\n|              3|face_to_face         |           8.161050|             31.79263|\n|              4|face_to_face         |           5.533329|             32.06459|\n|              5|face_to_face         |           6.342772|             21.33613|\n|              6|face_to_face         |           6.811127|             24.59724|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(communication_study) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|   |participant_id |communication_method |satisfaction_score |task_completion_time |\n|:--|:--------------|:--------------------|:------------------|:--------------------|\n|   |Min.   : 1.00  |Length:90            |Min.   :2.743      |Min.   :15.57        |\n|   |1st Qu.:23.25  |Class :character     |1st Qu.:5.840      |1st Qu.:23.38        |\n|   |Median :45.50  |Mode  :character     |Median :6.784      |Median :27.63        |\n|   |Mean   :45.50  |NA                   |Mean   :6.752      |Mean   :28.43        |\n|   |3rd Qu.:67.75  |NA                   |3rd Qu.:7.789      |3rd Qu.:32.65        |\n|   |Max.   :90.00  |NA                   |Max.   :9.936      |Max.   :47.41        |\n\n\n:::\n:::\n\n\n## The factorial study\n\nNovice and expert employees received either critical or positive feedback.\nAfterwards, their performance improvement was assessed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(factorial_study) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| participant_id|feedback_type |experience_level | performance_improvement|\n|--------------:|:-------------|:----------------|-----------------------:|\n|              1|positive      |novice           |                9.572290|\n|              2|positive      |expert           |                1.217696|\n|              3|positive      |novice           |                7.940961|\n|              4|positive      |expert           |                8.549420|\n|              5|positive      |novice           |                6.915946|\n|              6|positive      |expert           |                6.546548|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(factorial_study) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|   |participant_id |feedback_type    |experience_level |performance_improvement |\n|:--|:--------------|:----------------|:----------------|:-----------------------|\n|   |Min.   :  1.00 |Length:120       |Length:120       |Min.   :-1.882          |\n|   |1st Qu.: 30.75 |Class :character |Class :character |1st Qu.: 4.206          |\n|   |Median : 60.50 |Mode  :character |Mode  :character |Median : 6.937          |\n|   |Mean   : 60.50 |NA               |NA               |Mean   : 6.367          |\n|   |3rd Qu.: 90.25 |NA               |NA               |3rd Qu.: 8.757          |\n|   |Max.   :120.00 |NA               |NA               |Max.   :12.748          |\n\n\n:::\n:::\n\n\n\n**Short recap**: How have these data sets been created? How do they connect to experimental designs?\n\n::: {.callout-tip title=\"Possible answers\" collapse=\"true\"}\n- **Dataset 1**: Classic randomized controlled trial (RCT) with treatment and control groups\n- **Dataset 2**: One-way experimental design with three conditions (between-subjects)\n- **Dataset 3**: 2×2 factorial design allowing us to test main effects and interactions\n- **Connection to lecture**: These represent the three main experimental designs - simple, multi-group, and factorial\n:::\n\n---\n\n# Part 2: Simple Experiments - t-tests\n\nAssume we are asking the following research question:\n\n> Does leadership training improve team performance?\n\nOne way to tackle this question is to compare a treatment group, which has received a leadership training, to a control group, which has not received such training. If the groups are otherwise similar, then this setting should help us to identify the causal effect of the leadership training.\n\n## Descriptive statistics\n\nFor this task, we will use the first data set.\nLet us first compute the standard statistics:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescriptive_stats <- leadership_study_between %>%\n  group_by(group) %>%\n  summarise(\n    n = n(),\n    mean = mean(team_performance),\n    sd = sd(team_performance),\n    median = median(team_performance),\n    .groups = 'drop'\n  )\n\nkable(descriptive_stats, digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|group    |  n|  mean|   sd| median|\n|:--------|--:|-----:|----:|------:|\n|control  | 30| 74.53| 9.81|  74.26|\n|training | 30| 83.78| 8.35|  82.48|\n\n\n:::\n:::\n\n\nAs usual, it is also strongly recommended to complement the quantitative info with a visualization.\nData such as these is often presented using boxplots:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(leadership_study_between, aes(x = group, y = team_performance, fill = group)) +\n  geom_boxplot(alpha = 0.7) +\n  geom_jitter(width = 0.2, alpha = 0.5) +\n  stat_summary(fun = mean, geom = \"point\", shape = 23, size = 3, fill = \"red\") +\n  labs(title = \"Team Performance by Group\",\n       x = \"Group\",\n       y = \"Team Performance Score\",\n       caption = \"Red diamonds show group means\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](experiments-in-r_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nBut boxplots might shallow important distributional info, so you should use them carefully or complement them with other tools. Below is an alternative that provides more information on the distribution of the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  data = leadership_study_between,\n  mapping = aes(x = group, y = team_performance, fill = group)\n  ) +\n    stat_halfeye(\n    adjust = 0.5,\n    justification = -0.2,\n    .width = 0,\n    point_colour = NA\n  ) +\n  geom_boxplot(\n    width = 0.12,\n    outlier.color = NA,\n    alpha = 0.5\n  ) +\n  stat_dots(\n    side = \"left\",\n    justification = 1.1,\n    binwidth = 0.85\n  ) +\n  labs(\n    title = \"The effect of leadership training\",\n    y = \"Team performance\") +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(size = 11),\n    axis.title.x = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](experiments-in-r_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n\n## Assumption Checking\n\nIn the following we want to compare the means across independent groups.\nTo this end, we may use a t-test.\n\nBut such statistical tests make specific assumptions about the data. If these assumptions were violated, the results would be unreliable or incorrect.\nTherefore, it is important to check the adequacy of these assumptions for the data at hand first.\n\nIn the present case, we want to use a simple t-test. This test makes two assumptions:\n\n1. The two groups each are normally distributed.\n2. The variances of both groups are the same.\n\nTo test the first assumption, we can use the **Shapiro-Wilk Test for Normality**.\nHere we test the following hypothesis:\n\n- $H_0$ : The data is normally distributed\n- $H_1$ : The data is not normally distributed\n\nThus, if we get $p > 0.05$, we cannot reject $H_0$. But for smaller $p$-values,\nwe should reject $H_0$ and need to look for alternatives to the standard t-test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleadership_study_between |>\n  filter(group==\"control\") |>\n  pull(team_performance) |>\n  shapiro.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  pull(filter(leadership_study_between, group == \"control\"), team_performance)\nW = 0.97894, p-value = 0.7966\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleadership_study_between |>\n  filter(group==\"training\") |>\n  pull(team_performance) |>\n  shapiro.test()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  pull(filter(leadership_study_between, group == \"training\"), team_performance)\nW = 0.98662, p-value = 0.9614\n```\n\n\n:::\n:::\n\n\nGood! We cannot reject the hypothesis of normally distributed data as the $p$-value is much larger than $0.05$.\n\nThe next step is to test, whether both groups have the same variance.\nLevene's test can be used to do exactly this. It tests:\n\n- $H_0$: The variances are equal across groups\n- $H_1$: The variances are not equal across groups\n\nIf $p > 0.05$, we do not reject $H_0$ and we can use a simple t-test.\nIf we have to reject $H_0$, however, it would be better to use the more robust Welch test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::leveneTest(team_performance ~ group, data = leadership_study_between)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  1  1.0763 0.3038\n      58               \n```\n\n\n:::\n:::\n\n\nAgain, the $p$-value is much larger than $0.05$, so we can safely continue with the standard t-test.\n\n## Independent t-test\n\nThe standard independent t-test is the common tool to compare means between two groups when we have continuous data and want to test if there's a statistically significant difference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_test_result <- t.test(\n  team_performance ~ group,\n  data = leadership_study_between,\n  var.equal = TRUE # Use FALSE if variances unequal\n  )\nt_test_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  team_performance by group\nt = -3.9344, df = 58, p-value = 0.0002256\nalternative hypothesis: true difference in means between group control and group training is not equal to 0\n95 percent confidence interval:\n -13.962870  -4.545972\nsample estimates:\n mean in group control mean in group training \n              74.52896               83.78338 \n```\n\n\n:::\n:::\n\n\nThe very small $p$-value indicates that the difference of\n-9.25\nis highly significant!\n\n## Effect Size Calculation\n\nThe previous result tells us that the difference in\nmeans between the groups appears to be about\n-9.25. But is this a lot?\nEffect sizes tell us about the practical significance of our findings by relating the absolute numbers to the scale of the measurement.\n\nUnlike $p$-values, effect sizes are not influenced by sample size and help us understand if our statistically significant result is also practically meaningful.\n\nThe standard measure is **Cohen's d**: This standardized effect size tells us how many standard deviations apart the two group means are.\nIts interpretation follows a convention:\n\n- **Small effect**: $d\\approx 0.2$  (groups overlap about 85%)\n- **Medium effect**: $d\\approx 0.5$ (groups overlap about 67%)\n- **Large effect**: $d\\approx 0.8$ (groups overlap about 53%)\n\nThe implementation in R is trivial:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohens_d <- effectsize::cohens_d(team_performance ~ group, data = leadership_study_between)\nprint(cohens_d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |         95% CI\n--------------------------\n-1.02     | [-1.55, -0.47]\n\n- Estimated using pooled SD.\n```\n\n\n:::\n:::\n\n\nThe key value here is Cohen's d of -1.02!\nThis suggests a large and practically meaningful effect!\n\n## Paired t-test Example\n\nNext, we might want to look at our research question from a slightly different angle.\nRather than the between-subject design from above, we now take a *within-subject* view:\nto this end, we want to check whether the training had an effect on those people who were in the training (treatment) group by comparing their performance before and after the training.\n\nTo this end, we use the data set `leadership_study_within`, and then\nuse the function `t.test()` with the argument `paired = TRUE`.\nThis makes sure we are using the version of the test for the within-subjects context:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npaired_result <- t.test(\n  leadership_study_within$post_performance,\n  leadership_study_within$pre_performance,\n  paired = TRUE)\nprint(paired_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  leadership_study_within$post_performance and leadership_study_within$pre_performance\nt = 7.4774, df = 29, p-value = 3.059e-08\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 10.55898 18.51001\nsample estimates:\nmean difference \n       14.53449 \n```\n\n\n:::\n:::\n\n\nAs above, we should also compute standardized effect sizes.\nThere are two options: using the t-test object directly, or using the raw data.\nIf you do the latter, make sure to set `paired=TRUE` to use the correct version\nfor the within context:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohens_d_within_a <- effectsize::cohens_d(paired_result)\nprint(cohens_d_within_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |       95% CI\n------------------------\n1.37      | [0.86, 1.86]\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohens_d_within_b <- effectsize::cohens_d(\n  leadership_study_within$post_performance,\n  leadership_study_within$pre_performance,\n  paired = TRUE)\nprint(cohens_d_within_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |       95% CI\n------------------------\n1.37      | [0.86, 1.86]\n```\n\n\n:::\n:::\n\n\n\n**Exercise**: Interpret the results of the test above. What can we conclude about the effectiveness of leadership training?\n\n::: {.callout-tip title=\"Possible answers\" collapse=\"true\"}\n- **Statistical significance**: If $p < 0.05$, training significantly improved performance; since $p\\approx 0$, the training has a highly significant effect\n- **Effect size interpretation**: Cohen's d is large, so we have a large effect. This suggests the effect of the training is also practically meaningful.\n- **Confidence interval**: If the CI doesn't include 0, we're confident there's a real difference\n- **Business implication**: Training appears effective and worth the investment\n:::\n\n---\n\n# Part 3: Multi-Group Experiments - ANOVA\n\nLet us now turn to the following research question:\n\n> Which communication method (face-to-face, video call, email) leads to highest satisfaction?\n\nNote that this time we not only compare one group to another as in the previous section, but we need to compare three groups with each other as we have three different communication methods.\nTherefore, we cannot use simple t-tests, but need to use an ANOVA.\n\n## Descriptive statistics\n\nBut first, let us again look at the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunication_study %>%\n  group_by(communication_method) %>%\n  summarise(\n    n = n(),\n    mean = mean(satisfaction_score),\n    sd = sd(satisfaction_score),\n    min = min(satisfaction_score),\n    max = max(satisfaction_score),\n    .groups = 'drop'\n  ) |>\n  kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|communication_method |  n| mean|   sd|  min|  max|\n|:--------------------|--:|----:|----:|----:|----:|\n|email                | 30| 5.78| 1.46| 2.74| 8.73|\n|face_to_face         | 30| 7.48| 1.39| 5.14| 9.94|\n|video_call           | 30| 7.00| 1.10| 4.20| 9.50|\n\n\n:::\n:::\n\n\nAnd complement this by a visualization:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  data = communication_study,\n  mapping = aes(\n    x = communication_method,\n    y = satisfaction_score,\n    fill = communication_method,\n    color = communication_method)\n  ) +\n    stat_halfeye(\n    adjust = 0.5,\n    justification = -0.2,\n    .width = 0,\n    point_colour = NA\n  ) +\n  geom_boxplot(\n    width = 0.12,\n    outlier.color = NA,\n    alpha = 0.5\n  ) +\n  stat_dots(\n    side = \"left\",\n    justification = 1.1,\n    binwidth = 0.15\n  ) +\n  stat_summary(fun = mean, geom = \"point\", shape = 23, size = 3, fill = \"white\") +\n  labs(\n    title = \"Satisfaction Scores by Communication Method\",\n    x = \"Communication Method\",\n    y = \"Satisfaction Score (1-10)\") +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(size = 11),\n    axis.title.x = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](experiments-in-r_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n\n## ANOVA Assumptions\n\nANOVA is more robust than t-tests but still requires certain conditions to be met for valid results.\nIn fact, we are testing the same assumptions as in the t-test case:\n\n- **Normality of Residuals**: For ANOVA, we check if the residuals (not the raw data) are normally distributed.\n\n- **Homogeneity of Variances**: ANOVA assumes that the variance of the dependent variable is equal across all groups.\n\nLet us start with testing the normality of the residuals. We again use the Shapiro test, which tests the following hypothesis:\n\n- **$H_0$**: Residuals are normally distributed\n- **$H_1$**: Residuals are not normally distributed\n\nThus, if $p > 0.05$, the Null cannot be rejected and we can assume the residuals to follow a normal distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov_model <- aov(satisfaction_score ~ communication_method, data = communication_study)\n\nshapiro.test(residuals(aov_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(aov_model)\nW = 0.99149, p-value = 0.8342\n```\n\n\n:::\n:::\n\n\nSince $p>0.05$ we are on the safe side!\n\nWe then check the equality of variances and again use Levene's test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::leveneTest(satisfaction_score ~ communication_method, data = communication_study)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  2  1.8801 0.1587\n      87               \n```\n\n\n:::\n:::\n\n\nAgain, the Null cannot be rejected and we can continue with the ANOVA as planned.\n\n## One-Way ANOVA\n\nSince we compare three groups we do not use t-tests but an ANOVA.\n\nAs you know, ANOVA is actually a special case of linear regression.\nTherefore, we can get the ANOVA results in two equivalent ways.\n\nThe first option is to use the classical `aov()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_result <- aov(satisfaction_score ~ communication_method, data = communication_study)\nsummary(anova_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     Df Sum Sq Mean Sq F value   Pr(>F)    \ncommunication_method  2  46.29  23.146    13.2 9.81e-06 ***\nResiduals            87 152.50   1.753                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe second option is to use `lm()` as we know it from linear regression:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_model <- lm(satisfaction_score ~ communication_method, data = communication_study)\nanova(lm_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: satisfaction_score\n                     Df  Sum Sq Mean Sq F value    Pr(>F)    \ncommunication_method  2  46.292 23.1460  13.205 9.813e-06 ***\nResiduals            87 152.497  1.7528                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n- The overall $p$-value is extremely small, so the Null hypothesis of no difference between the groups should definitely be rejected\n- In other words: Communication method significantly affects satisfaction scores\n- This means that at least one communication method produces significantly different satisfaction scores than the others\n- But the result does not tell us which specific methods differ from each other (need post-hoc tests, see below)\n\n## Detour: categorical variables in Regression\n\nWhen you add a categorical variable as a predictor to your regression, R automatically creates dummy variables for categorical predictors. The first level alphabetically becomes the reference group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm_model)$coefficients |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|                                 | Estimate| Std. Error| t value| Pr(>&#124;t&#124;)|\n|:--------------------------------|--------:|----------:|-------:|------------------:|\n|(Intercept)                      |    5.776|      0.242|  23.895|              0.000|\n|communication_methodface_to_face |    1.702|      0.342|   4.980|              0.000|\n|communication_methodvideo_call   |    1.227|      0.342|   3.590|              0.001|\n\n\n:::\n:::\n\n\nSince 'email' comes first alphabetically, it is the reference group.\n\n- **Intercept** = mean of reference group (email, comes first alphabetically)\n- **communication_methodface_to_face** = difference between face_to_face and email\n- **communication_methodvideo_call** = difference between video_call and email\n\n### Detour: When to Use `lm()` vs `aov()`\n\nAs shown above, both approaches give identical results.\nStill, they offer different perspectives:\n\n**Use aov() when:**\n- You want traditional ANOVA output\n- Focus is on group comparisons\n- Need post-hoc tests such as `TukeyHSD()`, which take the `aov`-model as an input\n\n**Use lm() when:**\n- You want to see specific contrasts\n- Planning to add continuous covariates later\n- Want regression-style interpretation\n- Building toward more complex models\n\n\n::: {.callout-tip collapse=\"true\"}\n### Example: From ANOVA to ANCOVA\n\nIf we add a continuous variable to an ANOVA, we get an ANCOVA:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nancova_model <- lm(satisfaction_score ~ communication_method + task_completion_time,\n                   data = communication_study)\nsummary(ancova_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = satisfaction_score ~ communication_method + task_completion_time, \n    data = communication_study)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-3.07895 -0.87806 -0.00768  0.78530  2.90678 \n\nCoefficients:\n                                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                      5.628267   0.807830   6.967 6.15e-10 ***\ncommunication_methodface_to_face 1.737394   0.389664   4.459 2.48e-05 ***\ncommunication_methodvideo_call   1.253306   0.369901   3.388  0.00106 ** \ntask_completion_time             0.004472   0.023342   0.192  0.84853    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.331 on 86 degrees of freedom\nMultiple R-squared:  0.2332,\tAdjusted R-squared:  0.2064 \nF-statistic: 8.718 on 3 and 86 DF,  p-value: 4.108e-05\n```\n\n\n:::\n:::\n\n\nIn the example, we now control for individual differences in task completion time.\n:::\n\n\n## Effect Size for ANOVA\n\n$\\eta^2$ tells us what proportion of the total variance in the dependent variable is explained by the independent variable:\n\nRemember that:\n\n- **Small effect**: η² ≈ 0.01 (1% of variance)\n- **Medium effect**: η² ≈ 0.06 (6% of variance)\n- **Large effect**: η² ≈ 0.14 (14% of variance)\n\nIn our case:\n\n\n::: {.cell}\n\n```{.r .cell-code}\neta_squared <- effectsize::eta_squared(anova_result)\nprint(eta_squared)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA\n\nParameter            | Eta2 |       95% CI\n------------------------------------------\ncommunication_method | 0.23 | [0.11, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n$\\eta=$ 0.23 means communication method explains\n23\n% of the variance of satisfaction scores.\n\n## Post-Hoc Comparisons\n\nThe ANOVA tells us there's a difference somewhere among the groups, but not which specific groups differ.\nThis is why we need post-hoc tests:\nthey provide these pairwise comparisons while controlling for multiple testing.\n\n::: {.callout-tip collapse=\"true\"}\n### The multiple testing problem\n\nIf we do multiple t-tests (e.g. one for each pairwise comparison), our Type I error rate will inflate.\nPost-hoc tests adjust critical values to maintain overall $\\alpha = 0.05$.\n:::\n\n\nThe most common post-hoc test has a nice name:\nTukey's Honestly Significant Difference (HSD).\nIt takes the fitted ANOVA model as its input:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntukey_result <- TukeyHSD(anova_result)\nprint(tukey_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = satisfaction_score ~ communication_method, data = communication_study)\n\n$communication_method\n                             diff        lwr       upr     p adj\nface_to_face-email       1.702240  0.8871253 2.5173543 0.0000095\nvideo_call-email         1.227135  0.4120202 2.0422492 0.0015714\nvideo_call-face_to_face -0.475105 -1.2902195 0.3400094 0.3506328\n```\n\n\n:::\n:::\n\n\nThis suggests that the following differences exist:\n\n- Face-to-face > Email: 1.70 points higher satisfaction ($p < 0.001$)\n- Video call > Email: 1.23 points higher satisfaction ($p = 0.002$)\n\nBut there are no significant differences between video calls and face-to-face ($p = 0.35$)\n\nThus, both face-to-face and video call communication methods produce significantly higher satisfaction scores than email, but face-to-face and video call don't differ significantly from each other.\n\n# Part 4: Factorial Designs\n\nFor this last part we consider the following research question:\n\n> How do feedback type and experience level interact to affect performance improvement?\n\nWe use the data stored as `factorial_study`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfactorial_study %>%\n  group_by(feedback_type, experience_level) %>%\n  summarise(\n    n = n(),\n    mean = mean(performance_improvement),\n    sd = sd(performance_improvement),\n    .groups = 'drop'\n  ) |>\n  kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|feedback_type |experience_level |  n| mean|   sd|\n|:-------------|:----------------|--:|----:|----:|\n|critical      |expert           | 30| 6.53| 3.79|\n|critical      |novice           | 30| 5.53| 4.10|\n|positive      |expert           | 30| 6.69| 2.27|\n|positive      |novice           | 30| 6.71| 2.66|\n\n\n:::\n:::\n\n\nWe then visualize the relationship using an interaction plot as discussed in the lecture:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  data = factorial_study,\n  mapping = aes(\n    x = experience_level,\n    y = performance_improvement,\n    color = feedback_type,\n    group = feedback_type)\n  ) +\n  stat_summary(fun = mean, geom = \"point\", size = 2) +\n  stat_summary(fun = mean, geom = \"line\", linewidth = 1) +\n  stat_summary(fun.data = mean_se, geom = \"errorbar\", width = 0.1) +\n  guides(color = guide_legend(position = \"inside\")) +\n  labs(\n    title = \"Interaction Plot: Feedback Type × Experience Level\",\n    x = \"Experience Level\",\n    y = \"Performance Improvement\",\n    color = \"Feedback Type\") +\n  theme_minimal() +\n  theme(legend.position.inside = c(0.5, 0.2))\n```\n\n::: {.cell-output-display}\n![](experiments-in-r_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n\n## Two-Way ANOVA - Checking assumptions\n\nThe factorial design allows us to consider interaction effects among factors.\nBut to detect such interaction, we must use a two-way ANOVA!\n\nThe assumptions are in fact the same as in the previous case:\n\n1. Normality of *residuals* (not raw data)\n2. Homogeneity of variances (across *all* groups)\n\nTo fit the model with two factors:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfactorial_model <- aov(\n  formula = performance_improvement ~ feedback_type * experience_level,\n  data = factorial_study)\n```\n:::\n\n\n::: {.callout-tip title=\"Two-way ANOVA and linear regression\"}\n\nWhile the classical ANOVA was the same as simple linear regression with categorical variables,\ntwo-way ANOVA is the same as *multiple* regression with interaction effects:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_factorial <- lm(performance_improvement ~ feedback_type * experience_level,\n                   data = factorial_study)\nanova(lm_factorial)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: performance_improvement\n                                Df  Sum Sq Mean Sq F value Pr(>F)\nfeedback_type                    1   13.43 13.4301  1.2373 0.2683\nexperience_level                 1    7.12  7.1155  0.6556 0.4198\nfeedback_type:experience_level   1    7.88  7.8766  0.7257 0.3960\nResiduals                      116 1259.07 10.8541               \n```\n\n\n:::\n:::\n\n\nis the same as:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(factorial_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                Df Sum Sq Mean Sq F value Pr(>F)\nfeedback_type                    1   13.4  13.430   1.237  0.268\nexperience_level                 1    7.1   7.115   0.656  0.420\nfeedback_type:experience_level   1    7.9   7.877   0.726  0.396\nResiduals                      116 1259.1  10.854               \n```\n\n\n:::\n:::\n\n\n:::\n\nTesting normality of residuals:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(x = residuals(factorial_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(factorial_model)\nW = 0.98225, p-value = 0.1153\n```\n\n\n:::\n:::\n\n\nSince we test the same assumptions as above, $p>0.05$ means that we cannot reject the\n$H_0$ of normally distributed residuals.\n\nTesting homogeneity of variances:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::leveneTest(\n  performance_improvement ~ feedback_type * experience_level,\n  data = factorial_study)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value    Pr(>F)    \ngroup   3  6.2621 0.0005615 ***\n      116                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThis time $p<0.05$, so we need to reject $H_0$ of equal variances, meaning that some cells (in the sense of factor-combinations) have more variation than others.\n\n::: {.callout-tip title=\"Understanding the Variance Pattern\"}\n\nWe could have a look at which cells are affected like this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfactorial_study %>%\n  group_by(feedback_type, experience_level) %>%\n  summarise(\n    n = n(),\n    variance = var(performance_improvement),\n    sd = sd(performance_improvement),\n    .groups = 'drop'\n  ) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|feedback_type |experience_level |  n| variance|    sd|\n|:-------------|:----------------|--:|--------:|-----:|\n|critical      |expert           | 30|   14.392| 3.794|\n|critical      |novice           | 30|   16.791| 4.098|\n|positive      |expert           | 30|    5.156| 2.271|\n|positive      |novice           | 30|    7.078| 2.660|\n\n\n:::\n:::\n\n\nThis suggests that critical feedback is \"riskier\" - it might help some people a lot but hurt others.\n\nThis example shows how testing assumptions is not only relevant for its own sake, but also hints at interesting results themselves.\n:::\n\nSince the assumptions are violated, we use a version of the two-way ANOVA that is robust to unequal variances. We use the function `Anova()` from the `car` package with `type = \"III\"`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfactorial_model_robust <- car::Anova(factorial_model, type = \"III\")\n```\n:::\n\n\n\n\n## Two-Way ANOVA: Interpretation\n\nLet us now inspect the results of the two-way ANOVA.\nWe will pay particular attention to the following aspects:\n\n1. **Main effect of feedback_type**: Overall difference between positive vs critical\n2. **Main effect of experience_level**: Overall difference between novice vs expert\n3. **Interaction**: Does the effect of feedback depend on experience level?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfactorial_model_robust\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: performance_improvement\n                                Sum Sq  Df  F value Pr(>F)    \n(Intercept)                    1279.89   1 117.9186 <2e-16 ***\nfeedback_type                     0.37   1   0.0339 0.8542    \nexperience_level                 14.98   1   1.3803 0.2424    \nfeedback_type:experience_level    7.88   1   0.7257 0.3960    \nResiduals                      1259.07 116                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nFrom this output we see that all three effects (both main effects and the interaction) are non-significant, suggesting that:\n\n- Neither feedback type nor experience level significantly affects performance improvement\n- The combination of these factors doesn't create any synergistic effects\n- The observed differences in your sample means are likely due to random variation rather than true population differences\n\n# Part 5: Power Analysis and Sample Size Planning\n\nStatistical power is the probability of detecting an effect when it truly exists.\n\n## General aspects of power analysis\n\nRemember the **components of power analysis:**\n\n- **Power**: Probability of detecting effect (usually we want ≥ 0.8)\n- **Effect size**: How big a difference we want to detect\n- **Sample size**: Number of participants needed\n- **Alpha level**: Type I error rate (usually 0.05)\n\nWe can use power analysis in two different ways:\n\n1. **Post-hoc (observed)**: What was our power given the sample size we had?\n2. **A priori (prospective)**: How many participants do we need to detect an effect?\n\nRegarding the first, we may ask:\nwhat was our power to detect the effect we found in the leadership study?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobserved_power <- pwr.t.test(n = 30, d = as.numeric(cohens_d$Cohens_d), sig.level = 0.05)\nprint(observed_power)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 30\n              d = 1.015848\n      sig.level = 0.05\n          power = 0.9718339\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\nFor the\n*a priori power analysis*, you need to specify your research parameters:\n\n- What effect size do you want to detect?\n- What power level do you want? (typically 0.8 or 0.9)\n- What alpha level will you use? (typically 0.05)\n\n## t-Tests\n\nAssume we want to plan a new leadership training study.\nWe want to detect a medium effect ($d = 0.5$) with 80% power.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_size_medium <- pwr.t.test(d = 0.5, power = 0.8, sig.level = 0.05)\nprint(sample_size_medium)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 63.76561\n              d = 0.5\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\nAnd what would happen if we wanted higher power (90%) for a medium effect?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_size_high_power <- pwr.t.test(d = 0.5, power = 0.9, sig.level = 0.05)\nprint(sample_size_high_power)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 85.03128\n              d = 0.5\n      sig.level = 0.05\n          power = 0.9\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\nWe see that small design choices can have huge effects:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npower_results <- tibble(\n  Scenario = c(\"Medium effect, 80% power\", \"Small effect, 80% power\", \"Medium effect, 90% power\"),\n  Effect_Size = c(0.5, 0.2, 0.5),\n  Power = c(0.8, 0.8, 0.9),\n  Sample_per_Group = c(\n    ceiling(sample_size_medium$n),\n    ceiling(pwr.t.test(d = 0.2, power = 0.8, sig.level = 0.05)$n),\n    ceiling(sample_size_high_power$n)\n  )\n)\n\nkable(power_results)\n```\n\n::: {.cell-output-display}\n\n\n|Scenario                 | Effect_Size| Power| Sample_per_Group|\n|:------------------------|-----------:|-----:|----------------:|\n|Medium effect, 80% power |         0.5|   0.8|               64|\n|Small effect, 80% power  |         0.2|   0.8|              394|\n|Medium effect, 90% power |         0.5|   0.9|               86|\n\n\n:::\n:::\n\n\n\n\n## ANOVA\n\nAssume we are planning a communication study with 3 groups and we want to\ndetect a medium effect (f = 0.25) with 80% power.\nNote that what was Cohen's d for the t-test case, has now become Cohen's f for the ANOVA case:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_size_anova <- pwr.anova.test(\n  k = 3, f = 0.25, sig.level = 0.05, power = 0.8)\nprint(sample_size_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Balanced one-way analysis of variance power calculation \n\n              k = 3\n              n = 52.3966\n              f = 0.25\n      sig.level = 0.05\n          power = 0.8\n\nNOTE: n is number in each group\n```\n\n\n:::\n:::\n\n\nAside from that it works the same way as above!\n\n# Summary and Key Takeaways\n\n## Key take-aways\n1. **Data exploration** is crucial before statistical testing\n2. **Assumption checking** ensures valid results and guides method selection\n3. **Effect sizes** provide practical significance context beyond p-values\n4. **Visualization** aids interpretation and communication of results\n5. **ANOVA is just regression** with categorical predictors\n6. **Both aov() and lm()** give identical results but offer different perspectives\n7. **Post-hoc tests** control for multiple comparisons when making pairwise comparisons\n8. **Factorial designs** allow detection of interactions between factors\n\n## Key decisions to be made\n- **Assumptions violated**: Choose appropriate alternatives (Welch's tests, transformations, non-parametric)\n- **Multiple groups**: ANOVA preferred over multiple t-tests\n- **Factorial designs**: Allow testing of interactions between factors but requires two-way ANOVA\n- **Effect size interpretation**: Always consider practical alongside statistical significance\n- **Post-hoc testing**: Required when ANOVA is significant to identify which groups differ\n\n## Practice\n\nThis tutorial is accompanied by a practice exercise: analyze data from an experiment where employees were randomly assigned to three work environments (open office, private office, flexible workspace) to assess their effect on creativity scores.\n\nThe exercise asks you to:\n\n1. Explore the data and compute descriptive statistics for each group\n2. Check the assumptions (normality of residuals, equality of variances) before proceeding\n3. Conduct a one-way ANOVA using both `aov()` and `lm()` and verify they give identical results\n4. If significant, identify which groups differ using Tukey's HSD and calculate eta-squared as an effect size measure\n5. Create a visualization of the results and write a short interpretation\n6. As a bonus, add years of experience as a covariate (ANCOVA) and check if this changes your conclusions\n\n<script src=\"https://giscus.app/client.js\"\n        data-repo=\"graebnerc/research-methodology-hub\"\n        data-repo-id=\"R_kgDOS7J-4w\"\n        data-category=\"Comments\"\n        data-category-id=\"DIC_kwDOS7J-484C_N51\"\n        data-mapping=\"pathname\"\n        data-strict=\"0\"\n        data-reactions-enabled=\"1\"\n        data-emit-metadata=\"0\"\n        data-input-position=\"bottom\"\n        data-theme=\"preferred_color_scheme\"\n        data-lang=\"en\"\n        crossorigin=\"anonymous\"\n        async>\n</script>\n",
    "supporting": [
      "experiments-in-r_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}